### ISSUE TITLE
to_past turned "going" to "goinged"

### ISSUE THREAD

**Issue by drhayes** [nlp-compromise/compromise#115]
Awesome library! Messing around and found this one:

```
const nlp = require("nlp_compromise");
const s = nlp.statement('This is what is going on.').to_past().text();
console.log(s);
```

It logged "This was what was goinged on". I expected "This was what was going on."

**Comment by agarzola** [comment]
Wouldn’t it be more correct to say _This is what was going on._?

**Comment by drhayes** [comment]
Good question; it's kind of ambiguous. I could be totally wrong here. I think it's pluperfect past, or maybe past perfect progressive? Could be totally wrong.

"This is what was going on" is a certain kind of past tense. "This was what was going on" is another. They both express different things, so... I'm not sure if we know which the user wants when they invoke `to_past`.

**Comment by spencermountain** [comment]
this is a great example. it's certainly a task that seems straightforward until you start doing it ;)
i'll take a look

**Comment by spencermountain** [comment]
hey david and Alfonso! just getting back to this issue. This stuff matured a bit in v7, and this example behaves properly now:
https://runkit.com/583f2a3dc534df0014136221/58c826c2adbd8f00147ac4f7
but lots of bugs to find in there yet! Keep em coming!
thanks
