### ISSUE TITLE
Tense conversion incorrectly converts participles

### ISSUE THREAD

**Issue by hherman1** [nlp-compromise/compromise#131]
On the 'Tense conversion' demo from http://nlp-compromise.github.io/website/#demos the phrase 'He is running' is converted to 'He was ran', rather than 'He was running'.

**Comment by vladgolubev** [comment]
Another example.

![image](https://cloud.githubusercontent.com/assets/3817380/15318101/268674b2-1c2d-11e6-82f3-5182490a61ae.png)

**Comment by spencermountain** [comment]
aye! will take a look
thanks guys

**Comment by spencermountain** [comment]
hey, these both work now, 
https://runkit.com/spencermountain/59a15ab99966ee001215066f
cheers
