### ISSUE TITLE
Site doesn't work on older browsers

### ISSUE THREAD

**Issue by Haroenv** [nlp-compromise/compromise#134]
`let` is just an example of code that doesn't work if the browser doesn't implement ES6 fully. 

You could use a transpiler like Babel to fix this.

**Comment by spencermountain** [comment]
hey Haroen, thanks. i've made some fixes, but there's still some babel/es5 issues. am on it.
cheers

**Comment by Haroenv** [comment]
great!

**Comment by spencermountain** [comment]
hey Haroen, took me some time, but i spent the weekend running v7 in saucelabs in retro ie9 versions.
all good ie9+
thanks!

**Comment by Haroenv** [comment]
Yay! Thanks for bringing me to attention of this project again
