### ISSUE TITLE
Text with mixed (expanded/contracted) contractions

### ISSUE THREAD

**Issue by factormystic** [nlp-compromise/compromise#147]
I'm having a difficulty with this test text: `he's got a gun that he is going to use.`

If I just dump out the terms ([link](https://tonicdev.com/573a6c9c8b73ef120061ca7a/573d2127691f641100ada8b6)), I see that `he's` is represented with 2 terms, which is kind of odd. But I see the `expansion` property (undocumented?) is populated... is that what that's about, saying those two terms are part of the single word?

If I wanted to, say, count words... how can I tell that terms are part of the same word? Adjacent in the `terms` array + `expansion` is populated + ?

Secondly, if I expand the text ([link](https://tonicdev.com/573a6c9c8b73ef120061ca7a/573d1ed100710d1500c112dc)), the two `he is`'s get parsed differently. The first Term, Verb and the second is Person, Verb (tagged as copula). That's surprising because I would have expected in this case for those to come out equivalently. Not saying it's wrong, just that I was surprised.

Third, the expansion of the first `he's` to `he is` could be improved to `he has` due to the following `got`.

**Comment by spencermountain** [comment]
yep, this is a huge error. Thank you for documenting it so clearly.

Yeah, contractions need to be split apart into two terms for proper interpretation of their grammar. If you want a real word-count, you could loop through the terms and not include the ones with a expansion-field, and no text... but maybe that's a good candidate for a helper-method... ya this is probably a good idea I think.

yeah, "apostrophe s" is a really ambiguous thing, not just with possessives, ("spencer's",) but with `he has, he is, he was..` etc. I've done a bit of work at pulling these apart, but not enough, as it looks like your example is parsed incorrectly.

Pretty solvable, this stuff, but we're still rounding-third base with the proper, smooth contraction support. It presents problems not just here, but all over the codebase ;)

will keep this open. 
thanks!

**Comment by spencermountain** [comment]
hey, just going back to this example, it's a doozy.
you can see it's [better now](https://runkit.com/spencermountain/59efdae519147900121446dd) but the `expand()` method is pretty conservative when it comes to ambiguous cases like 'he has'.
closing this for now.
thanks!
