### ISSUE TITLE
Incorect Negation for negated things.

### ISSUE THREAD

**Issue by epicTCK** [nlp-compromise/compromise#152]
`apples are not bad` becomes `apples aren't not bad`

**Comment by spencermountain** [comment]
hey Caleb, thanks. Yep, Ilya got this in his PR, but the whole 'un-negation' concept really still needs a lot of work. Yeah, maybe this should stay open.
cheers!

**Comment by spencermountain** [comment]
hey Caleb, this is a bit cleaner now in version 10+
https://runkit.com/spencermountain/59a1691ab912cc0012b2c572
not perfect, but better!
cheers
