### ISSUE TITLE
apply type-definitions to test runner

### ISSUE THREAD

**Issue by spencermountain** [nlp-compromise/compromise#165]
maintaining a `d.ts` file is a pretty cool way to add both documentation and type-safety to nlp_compromise, while allowing uses in other frameworks and tooling.

the tests then should either run in typescript, or somehow hook into the d.ts file, to notice when the typefile gets invalidated. That gives us a pretty lucid definition and understanding of the api, and when it changes.
#162

**Comment by eshansingh** [comment]
If you're using gulp or grunt, you can make a TypeScript file called `nlp_compromise-typings.test.ts` somewhere, and then have gulp/grunt `test` run `tsc` (the TypeScript compiler) on it, and make sure it runs with no errors. See [DT Contribution Guide - Tests](http://definitelytyped.org/guides/contributing.html#tests).

**Comment by eshansingh** [comment]
I have added a gulp task (`gulp test`) to [the typings repo](https://github.com/2426021684/nlp-compromise-typings/) Let me know if you use `grunt` or something else. For now the way is to run `gulp test` and make sure it exits with no errors.

**Comment by spencermountain** [comment]
thanks!! that's brilliant Eshan.
