### ISSUE TITLE
Looks like normal and root method doesn't work

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/compromise#182]
Hi,

Firstly, great job!!! I'm using `Compromise` but I have severa issues.
- `root()` for the string `It's raining in Bangkok` returns `It' is raining in Bangkok` (I wonder that should be `it`)
- `normal()` doesnt exists in object `nlp`

Thanks, in advance :)

**Comment by spencermountain** [comment]
hi Javi! oof, I'll take a look. 
thanks

**Comment by spencermountain** [comment]
hey, fixed the apostrophe issue, now it returns
* `"it is raining in bankok"`
yeah, the normalization is on the text, term & sentence objects
`nlp.text(`Dr. John Smith is   five feet tall.`).normal()`
let me know if there's an unclear documentation hanging around for that
cheers

**Comment by soyjavi** [comment]
Looks like that `normal` method still being undefined :(

```
console.log(nlp.text("Dr. John Smith is five feet tall.").normal
> undefined
```

**Comment by spencermountain** [comment]
hey Javi, it's a method - `nlp.text('').normal()`

**Comment by soyjavi** [comment]
@spencermountain I know :), but if you test if `normal` exists returns `undefined` so it's quite difficult try to execute `undefined` :). I wonder that maybe `text()` method doesn't return the instance.

**Comment by 2426021684** [comment]
I can confirm this issue

**Comment by spencermountain** [comment]
ahhh!
sorry about that!
just pushed a fix, will be available in v6.0.0, maybe this evening.
in the meantime, `nlp.text('').normalize()` ;)
thanks for your patience!

**Comment by 2426021684** [comment]
@spencermountain You forgot to change where normalize is called.
```
> nlp.text("normal").normal()
TypeError: s.normalized is not a function
    at /Users/michaelmesser/Sources/nlp_compromise/src/text/text.js:57:16
    at Array.map (native)
    at Text.normal (/Users/michaelmesser/Sources/nlp_compromise/src/text/text.js:56:32)
    at repl:1:20
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

**Comment by 2426021684** [comment]
@spencermountain You forgot to change where `normalized` is called.
```
> nlp.text("normal").normal()
TypeError: s.normalized is not a function
    at /Users/user/Sources/nlp_compromise/src/text/text.js:57:16
    ...
```

**Comment by 2426021684** [comment]
@spencermountain should term.normalize be replaced with term.normal?

**Comment by spencermountain** [comment]
thanks, just lookin at this now

**Comment by factormystic** [comment]
Also, the docs still reference `normalized`

**Comment by spencermountain** [comment]
hey, `.normalize()` got a big re-write in v7, and its behaviour has changed a fair amount.
https://runkit.com/583f2a3dc534df0014136221/58c826413d42f900147f994c
gonna close this issue, but lemme know if you find any trouble in the new one
thanks guys!
