### ISSUE TITLE
Mixed-Case names

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/compromise#220]
Hi,

I played with the website and get different results for the same sentence (only switch lowerCase/upperCase):

<img width="349" alt="screen shot 2016-06-18 at 11 02 40" src="https://cloud.githubusercontent.com/assets/559654/16168922/5ca1f078-3544-11e6-8b3e-53e12705bc2a.png">
<img width="350" alt="screen shot 2016-06-18 at 11 02 48" src="https://cloud.githubusercontent.com/assets/559654/16168921/5ca055e2-3544-11e6-9780-a5ee36452d75.png">
<img width="323" alt="screen shot 2016-06-18 at 11 02 54" src="https://cloud.githubusercontent.com/assets/559654/16168920/5c9d66de-3544-11e6-9ff9-67212a563b3e.png">

Also if we _normalize_ a determinate sentence with `normal()` we have different results. Let's play with the sentence `tell me something about Leonardo Dicaprio` and the `tags()` method:
### .normal() + tags()

``` js
[ 'Person',
    'Infinitive',
    'Pronoun',
    'Possessive',
    'Preposition',
    'Person',
    'Noun' ]
```
### only .tags()

``` js
[ 'Person',
    'Infinitive',
    'Pronoun',
    'Possessive',
    'Preposition',
    'Person' ]
```

Any idea, how we can fix this?

**Comment by spencermountain** [comment]
yeah, this is tough. -  well for one, Plural is wrong. Not sure why.
but capitals are things that usually shouldn't be lumped together. Your example is a good one, but we do place some faith in a capital as a grammatical signal -  and more and more it seems an old-fashioned concept.

**Comment by soyjavi** [comment]
Understand, It looks like difficult to fix ... but... how about `normal + tags` and `tags`??

**Comment by spencermountain** [comment]
yeah, i think it means something different after you normalize it.

**Comment by spencermountain** [comment]
hey Javi, this is working now in v7
https://runkit.com/583f2a3dc534df0014136221/58c6d77c90bd3000131487e9
cheers
