### ISSUE TITLE
Syntax matching issue

### ISSUE THREAD

**Issue by soyjavi** [nlp-compromise/compromise#235]
Hi,

I'm trying to use `match` method and I've several problem with the selector. For example:

`How can I translate into italian i have hungry`

the match I use is `translate [Preposition]? [Demonym]` and its _succesful_ 💪. But for sentence:

`how can translate hello world into german`

I use a different match `translate * [Preposition]? [Demonym]` but doesn't work, I read that using `*` means 'all terms until'.

Thanks for your support,

**Comment by spencermountain** [comment]
yeah...  * isn't even supported yet.
😓 
punting this for now.

**Comment by spencermountain** [comment]
hey Javi, this works now:
https://runkit.com/583f2a3dc534df0014136221/58c823feee89c00015029346
woot!
cheers
