### ISSUE TITLE
Conjugation from non-infinitive form verbs

### ISSUE THREAD

**Issue by shaharyakir** [nlp-compromise/compromise#243]
"Swim" conjugation works well, but "Swimming" turns to "Swimm", "Puking" turns to "Puk", etc.

**Comment by shaharyakir** [comment]
Any chance to include the quick fix soon? :)

**Comment by spencermountain** [comment]
hey, sorry about this.
this fix will be in v7, but will be a week away or so. if you need a quick fix, you can just add them to [./data/irregular_verbs.js](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/data/irregular_verbs.js), then run `grunt build`
cheers

**Comment by shaharyakir** [comment]
Sounds great. Thanks!

**Comment by spencermountain** [comment]
hey Shahar, sorry for the delay.
this is fixed in `v8.2.0`
thanks!
