### ISSUE TITLE
How to handle the QU object?

### ISSUE THREAD

**Issue by videophonegeek** [nlp-compromise/compromise#248]
Complicated subject. In the past I had some in the pronoun class like WHO, Whom, and others in the noun class.

'QU': ['where', 'why', 'when', 'who', 'whom', 'whose', 'what', 'which'],

They all appear as type "Question" when terms are expanded. There are a couple more of this class too. Excuse my additions to the objects--these are done for clarity after the nlp-compromise calls.
![whowhom](https://cloud.githubusercontent.com/assets/191271/17077313/badf4964-5106-11e6-89c4-8f0e79eece21.PNG)

**Comment by spencermountain** [comment]
hey, yeah great. do you have a list here too?
i was a bit cautious with these words, because some are ambiguous, but happy to improve things.

**Comment by videophonegeek** [comment]
Hi Spencer,

I have megabytes of lists but they are organized so a word or concept could appear on multiple lists. What I can do, is given a list of words, return an object containing all the lists the word appears on. For example, "when" appears on the noun and adverb lists, "who" appears on pronoun and noun.  If it would be helpful, I can screen the QU list against my data for pos, and make some additions.

**Comment by spencermountain** [comment]
thanks, of course if you find something helpful, please share. I've used the [illinois question set](https://github.com/nlp-compromise/nlp_compromise/blob/master/test/perf_tests/question_test/questions.js), but i think the current QU words are just eyeballed, and may have holes.

**Comment by spencermountain** [comment]
moving this to #399
