### ISSUE TITLE
extra conjunctions

### ISSUE THREAD

**Issue by videophonegeek** [nlp-compromise/compromise#249]
For-and-nor-but-or-yet-so. In the CC category, "so" is not included as a conjunction. This is my list of conjunctions which is not complete as there are some wildly complicated connectors too.

After
Although
And
As
As far as
As if
As soon as
Because
Before
But
Even if
For
How
If
In case
In that
No matter how
Nor
Now that
Once
Or
Provided
Since
So
So that
Supposing
Though
Unless
Until
When
Wherever
Whether
While
While
Yet

**Comment by spencermountain** [comment]
ha, that's great. I'll take a look at this in a day or so. If you diff them with the current lexicon, I think most but not all are covered. Thanks John!

**Comment by spencermountain** [comment]
hey John, added a few of these we've been missing.
thanks!
