### ISSUE TITLE
Documentation for lexicon update needing lowercased keys

### ISSUE THREAD

**Issue by elderbas** [nlp-compromise/compromise#250]
Hey

I'm new to the nlp library as well as NLP in general.
It wasn't clear to me as a new NLP user that the example in the documentation for 
adding 'apple' as a lexicon value of 'Person' had 'apple' lowercased by necessity. I was passing in capitalized words to my key and they weren't being "detected" as having been added.

Worth it for me to add a little comment in that section? I mention I'm new because maybe it's a known thing that they need to be normalized before being added to lexicon.

**Comment by spencermountain** [comment]
ah, thanks brian. Good point. I've added this to [the documentation](https://github.com/nlp-compromise/nlp_compromise/wiki/Lexicon), but It's pretty opaque right now, isn't it.
moving things around shouldn't require any in-depth knowledge of internals, or crossing-of-fingers. I'm knees-deep in [a re-write](https://github.com/nlp-compromise/nlp_compromise/blob/v7/README.md) and maybe this should be part of it.
thanks,

**Comment by spencermountain** [comment]
hey brian, just getting around to this now.
this is fixed in v7+, I just loop-around the lexicon and if the word is uppercased, we normalize it internally. There may be some bugs, but you can see that this is working now:
https://runkit.com/583f2a3dc534df0014136221/58c82220ee89c0001502925b
cheers!
