### ISSUE TITLE
Easy fix in keypress demo

### ISSUE THREAD

**Issue by videophonegeek** [nlp-compromise/compromise#251]
Correction like this:  
 src="../builds/nlp_compromise.js"

Add the extra . in the directory reference so the example runs right out of the box and finds nlp_compromise.js.

PS:  Just looked and the same is true in the API demo.

**Comment by spencermountain** [comment]
yeah, i think someone changed that to use a symlink to `./builds`. is it not working for you?

**Comment by videophonegeek** [comment]
I guess only if you do an NPM install?

**Comment by spencermountain** [comment]
hmm. good question...

**Comment by spencermountain** [comment]
hey John, finally pointed these at the unpkg cdn, so no more symlinks
thanks!
