### ISSUE TITLE
New demo

### ISSUE THREAD

**Issue by videophonegeek** [nlp-compromise/compromise#252]
If this helps someone...stripped down from my gui, but unsure when to add stuff and not cause merge headaches? This really illustrates the power of this Javascript project.

[simple_demo2.txt](https://github.com/nlp-compromise/nlp_compromise/files/380576/simple_demo2.txt)
![simpledemo](https://cloud.githubusercontent.com/assets/191271/17087579/70a72810-5248-11e6-9f4a-ad6c8cd9ee68.PNG)

**Comment by spencermountain** [comment]
hey John! I'm sorry, i'm not sure how I missed this a few months ago!
nicely done! Thanks for sharing, and the kind words.
