### ISSUE TITLE
v7 API syntax discussion.

### ISSUE THREAD

**Issue by lukaswelinder** [nlp-compromise/compromise#262]
This is just an opinion on style, so feel free to disagree, but I find the capitalization of the string actions `.to('Adverb')` or `.to('PastTense')` to be a bit confusing in comparison to the previous API (lowercase w/ underscores).

My main reasoning behind that is the possibility of misspellings. I can see the argument for the style; it's in line with most style guide's stance on the capitalization of constructors. However, because they are just constant value primitives, I feel like it would be more appropriate to lean towards that approach.

My proposal:

Using the syntax, with those keywords being constants, I would set a value `const PAST_TENSE = 'PAST_TENSE'` (similar to the recommended pattern of action types in Redux). It leads to a more extensible, error free approach. This isn't to say I won't do this regardless, but it feels strange doing `const PAST_TENSE = 'PastTense'`.

I'd love to hear other opinions.

**Comment by lukaswelinder** [comment]
One other thought that came to me after reviewing the proposal:

When performing targeted transforms `.to('Noun').to('Plural')` there should instead be a selector method to specify what the transform will operate on like `.transform('Noun').to('Plural')`.

To take that a step further, that selector method should accept a matcher or a custom lexicon to allow for things like `.transform('[Place] [Verb] [Adjective]').to('PastTense')`.

I'll be playing around with the v7 branch over the weekend to see how this might be implemented.

**Comment by spencermountain** [comment]
Lukas, thank you so much. This is very timely, and exactly where I've been reckoning lately.

Yeah, the strings-as-methods is pretty error-prone, and I'm torn about it as well. It would definitely normalize case, and maybe even support a bunch of aliases, to *soften it up*. I've been doing a console.warn [when there's a miss](https://github.com/nlp-compromise/nlp_compromise/blob/new_chaining/src/models/term/index.js#L95) but all the structural javascript stuff will be lost. I tried adding all the methods `toNoun`, `toPlural` ... but that became a bit of a hot-mess.

Your second idea is also on point. The dream is to have this exact `filter -> transform` process really, really easy. - Where you can *reach in* and grab the right stuff, and do the particular things.
```javascript
var all= nlp(myNovel)
//first transform
all.find('#place #verb #adjective').to('pasttense')
//second transform
all.find('#adverb #adjective').to('opposite')
// ... then
all.print('html')
```

So where I've gotten to [lately](https://github.com/nlp-compromise/nlp_compromise/tree/new_chaining) is forcing all interactions to go this way. This means that a single term/word is really just `.find()` result of length 1, you know? There's no term api anymore. And further - all the lumping/splitting of terms we did (about half the work of nlp_compromise previously) is no longer needed. 
`.find('#Verb')` now can return any combination of terms we decide is useful. We no longer need to wrangle about which combinations of terms makes a `Verb`. It's okay for it to be 5 words, like `will have had quickly walked`, or non-consecutive terms, like `will, if necessary, walk`.

Lastly (it's nice to air this out), I'm confused about how, like in your example, `[Place] [Verb] [Adjective]`, it would know how to conjugate that - like, a place can't be conjugated, just like a Adverb can't be made plural, and so on. Sometimes the results are full sentences, or single terms. I don't know exactly how a `toPast` method should understand what it's dealing with, before going to town on it. 

All solvable problems, but I'm pretty keen on getting it right. And I'm definitely not going to get it right without some feedback
thanks,

**Comment by lukaswelinder** [comment]
> This means that a single term/word is really just .find() result of length 1, you know?

Not sure I follow you here. Seems a little unclear to reason about (considering the example below). Would it (selecting verb) lump words together if they are part of the same action and handle / return unrelated verbs as an array?

I like the idea of being able to manually handle the terms/data with something like `.terms()`, so I'm curious to see how you envision that. I should have some free time tomorrow afternoon to start digging into what you have going.

> Lastly (it's nice to air this out), I'm confused about how, like in your example, [Place] [Verb] [Adjective], it would know how to conjugate that - like, a place can't be conjugated, just like a Adverb can't be made plural, and so on.

Hmm. I was seeing it as: 'return and operate on anything that matches this sequence exactly'. So it would only be operating on the three words (multiple found as array of 3 words - circles back to my question further up however). With that particular example, the final sentence could very well be incorrect grammar, but it gave the user control over what phrases to parse.

I don't know enough about the implementation at present, but I imagine that the best course of action would be operating on each identified selection with something resembling the existing method `.text(/* selected snippet text */).to_past()`.

Let me think on it a bit more. It's difficult to say what the best approach is considering your move away from the `.terms()` API. I can probably provide some better feedback after reviewing the codebase a bit more; I'll try to circle back early next week.

**Comment by lukaswelinder** [comment]
@spencermountain Reviewing the documentation on the V7 branch, I wanted to follow up with some of my thoughts on where it's at now. My apologies for not getting any coding in; I've been incredibly busy, but I'd still like to contribute where I can with regard to the API design in the meantime.

Firstly, I'm a little torn on how the `.render()` method works here:

```
nlp('john is cool').render('PAST_TENSE');
nlp('john is cool').render('QUESTION');
```

It's unclear what to expect the return value to be when considering `.render('text')` mentioned previously. This functionality (transforms using `.render()`) feels too similar to the `.to()` method.

On the other hand, I really like the `.if()` method. However, the description in the docs is a bit unclear, so let me see if I am understanding it correctly. 

Say for example I do `nlp('John ran and Mary jumped.').if('VERB')`, would this operate on both 'ran' and 'jumped', or just the first encountered verb? 

I feel the later would be preferable, but perhaps there should be some notation that indicates global lookup (ie in regex `/selector/flag`.

In extension of that, what would happen should someone want to chain together `.if()` selectors and transforms? Would the transform release the selector such that a new selection can be made?

```
nlp(' . . . ')
  .if('NOUN').to('PLURAL') // transform all nouns
  .if('VERB').to('PAST_TENSE') // then all verbs
  .render('TEXT');
```

How about chained selections like `nlp(' . . . ').if('QUESTION').if('PERSON')`? Just want to make sure i understand your plans there correctly before diving into discussion on the `.match()` method's possible implementations.

Let me know if you've had any breakthroughs or revelations recently; really looking forward to seeing how this new API plays out.
