### ISSUE TITLE
Getting location of results in the string

### ISSUE THREAD

**Issue by alejandroiglesias** [nlp-compromise/compromise#263]
Hi, this library seems what I need to analyse entered data, but the only thing that I couldn't seem to find in the docs is how to get the location of the result.

Let's say I do this:

```
nlp_compromise.text('That is Tony dancing.').people()
```

I get:

```
[  
   {  
      "whitespace":{  
         "preceding":"",
         "trailing":" "
      },
      "text":"Tony",
      "normal":"tony",
      "expansion":null,
      "reasoning":[  
         "capital_signal",
         "lexicon_pass"
      ],
      "pos":{  
         "Noun":true,
         "Person":true
      },
      "tag":"Person",
      "honourific":null,
      "firstName":"Tony",
      "middleName":"",
      "lastName":null
   }
]
```

How can I know that the tag is related to position 8 of my string? Does nlp_compromise offer any API for that?

And besides that, I would basically need to replace the occurrences (`Tony` in this case, or any people, organization, dates and places) with a markup (on the lines of <mark>Tony</mark>). I've checked the `match`/`replace` APIs but they don't seem to work the way I would need in this case. Is there a possible workaround or I have to look into another library?
Thanks a lot.

**Comment by spencermountain** [comment]
hey Alejandro! sorry for the delay in getting to this.
it's a great point. thinking about offsets is the biggest pain-point I've had in using this library myself. 
The short answer is that it's not something that's solved very well in nlp_compromise yet. The longer answer is that I hate the idea of having to count characters in the original string, to get back to the text. In a perfect world, if you're highlighting specific words or something, you regenerate the whole text from nlp_compromise, with those words highlighted. You know? There shouldn't be two places where the data is, just one.

it's too raw to use yet, but [the latest version](https://github.com/nlp-compromise/nlp_compromise/tree/v7) is built with a `.render()` method, which (i hope) should handle your use-case without having to count characters. You should be able to grab your text, make your transformations, then present it properly in one go. it's a couple weeks off yet, though :sweat: 

in the meantime, it's conceivable to count the offset just by looping through each sentence and each term, and creating a sum. I'd be happy to help with this.
let me know if you figure out a solution,
cheers

**Comment by spencermountain** [comment]
(if you create the offsets yourself, `Term.text` should be character-perfect with the original, short of some edge-cases with unicode things)

**Comment by spencermountain** [comment]
hey Alejandro!
sorry I've taken some time with this, but offsets are now supported in v7+ with the `.out('offset')` method
here's an example of it working
https://runkit.com/583f2a3dc534df0014136221/58c820c6ee89c000150291c4
thanks!

**Comment by alejandroiglesias** [comment]
Thanks @spencermountain! Will try it when I get back to the experiment I was doing.

**Comment by retorquere** [comment]
How can I use this when just tokenizing with `compromise/one`?

**Comment by spencermountain** [comment]
hi Emiliano, the process should be the same using `/one`, just you won't have any tags in the document.
please see https://observablehq.com/@spencermountain/compromise-offsets for the documentation
cheers
