### ISSUE TITLE
terms with trailing punctuation fail has_abbreviation()

### ISSUE THREAD

**Issue by jiminys** [nlp-compromise/compromise#268]
Terms such as "**she'll,**" fail expansion due to the training comma. Simple fix would be to add "`[,;]*`" (or equivalent, not tested!) to the end of the regex [here](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/term/term.js#L80). 
Longer term fix would be to think about segmenting sentences into sub-clauses?

Happy to pull request the former and discuss the latter!

**Comment by spencermountain** [comment]
wow, jiminys I don't know how I missed this issue, i'm sorry.
still failing as of v10! will check it out today.

**Comment by spencermountain** [comment]
oof, got it. 
will be in `v11`.
cheers
