### ISSUE TITLE
Trailing newlines are ignored

### ISSUE THREAD

**Issue by dbkaplun** [nlp-compromise/compromise#271]
Input: `"This is a test.\n"`
Expected: `[..., {..., "whitespace": {..., "trailing": "\n"}}]`
Actual: `[..., {..., "whitespace": {..., "trailing": ""}}]`

https://runkit.com/dbkaplun/57eee395ad67621400b7f29c

**Comment by spencermountain** [comment]
agh, nice find.
ooh! unglish is cool! I really like this idea.
and yeah, the [hard-part](https://github.com/dbkaplun/unglish/blob/master/src/front/Unglish.jsx#L96) is this whitespace-offset-cursor-stuff that never seems to go away on the web ;)
I'll look at fixing this bug. please let me know if there's anything else I can do to help
cheers

**Comment by spencermountain** [comment]
it's not ready yet, but fwiw, [v7](https://github.com/nlp-compromise/nlp_compromise/tree/v7) is [trying to](https://github.com/nlp-compromise/nlp_compromise/blob/v7/src/models/term/render/renderHtml.js) support html output too. The whitespace, encode/decoding, sanitization, and funky unicode and things make it a little treacherous, and it's definetly a use-case i'd like nlp_comp to do, pronto. (and would love some help)

**Comment by spencermountain** [comment]
hey dan! sorry for the delay on this, 
all good now!
https://runkit.com/583f2a3dc534df0014136221/58d5d05354c1be00146c4a6f
cheers
