### ISSUE TITLE
Optional ordering of n-grams?

### ISSUE THREAD

**Issue by owendall** [nlp-compromise/compromise#283]
related to V7 ngram.js

```
var preamble =  "We the People of the United States, \
                            in Order to form a more perfect Union, establish Justice, \
                            insure domestic Tranquility, provide for the common defence,\
                            promote the general Welfare, and secure the Blessings of Liberty to \
                            ourselves and our Posterity, do ordain and establish this Constitution for the \
                            United States of America.";

  var bigrams = nlp(preamble).ngram({size:2});
```

Right now we get the three attributes as such:

count: 2, size: 2, text: "for the"

How about a boolean flag to keep the order of the bigrams. Something like:

`var bigrams = nlp(preamble).ngram({size:2, order:true});`

 But them the attribute "count' would no longer be relevant:

`order: 4, size: 2, text: "for the"`

Thoughts?

**Comment by spencermountain** [comment]
ah, like chronological order! of course.
... ordered by first-mention?
i can do that.

**Comment by owendall** [comment]
Great!

**Comment by spencermountain** [comment]
hey, i think this is working now, can you take a look?
```js
nlp(myText).ngrams().sort('chronological').data()
```
thanks
