### ISSUE TITLE
Error in sentence -> root()

### ISSUE THREAD

**Issue by TheAmenRa** [nlp-compromise/compromise#287]
I tried this: 

```
var string = 'I am walking.' 
var sentence = nlp.sentence(string) 
var root = sentence.root() 
console.log(root);
```

The output is "i am walk", but i think the correct output should be 'i be walk'.
Same thing with "You are walking.", "She is walking." and so on. ('was', 'were')

**Comment by spencermountain** [comment]
hi Elias, thanks for this.
i laughed out loud when i looked into this and found [this comment](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/data/irregular_verbs.js#L30) ;) 
you're right about this. I'm gonna punt it to the v7 release, as it's a bit chunky, and there's some relevant changes happening there.
will leave this open

**Comment by spencermountain** [comment]
hey Elias, got this working a little differently now, since v7.
```js
var nlp=require('compromise')
var sentence = nlp('I am walking.') 
var root = sentence.out('root') 
```
you can see it in action [here](https://runkit.com/spencermountain/59efd95a23124e00116499e1)
cheers
