### ISSUE TITLE
Wildcard matching with "*" is not working 

### ISSUE THREAD

**Issue by pasupulaphani** [nlp-compromise/compromise#291]
Tried the example given https://github.com/nlp-compromise/nlp_compromise/wiki/Match-syntax

Looks like it is not working.

```
nlp.text('John always ravenously eats his glue').match('john * eats')
// [null]
```

**Comment by spencermountain** [comment]
hey Phaninder, thanks!
the documentation quality has gotten really brutal. I've re-written the matching syntax stuff in [the v7 branch](https://github.com/nlp-compromise/nlp_compromise/tree/v7), which i hope to release in a few weeks. I'll keep this open until things are cleaned-up. in the meantime, you can do it in v7:
```javascript
console.log(nlp('John always ravenously eats his glue').match('john * eats').plaintext());
//John always ravenously eats
```

**Comment by pasupulaphani** [comment]
Thank you @spencermountain

**Comment by spencermountain** [comment]
hey Phaninder, this is all working now!
https://runkit.com/583f2a3dc534df0014136221/58c82b403d42f900147f9afd
thanks for your help
