### ISSUE TITLE
Emoji in parts of speech tagger

### ISSUE THREAD

**Issue by kahwee** [nlp-compromise/compromise#296]
I understand this isn't possible at the moment, is there plans for tagging emojis as it is?

I'm thinking we can leverage on [this](https://github.com/wooorm/emoticon) to tag what emoji it is as well.

**Comment by kahwee** [comment]
Thank you @spencermountain for implementing this so quickly!

**Comment by abushoeb** [comment]
Just wondering if you have any update on this. Looking forward to it and happy to help if required :-)

**Comment by spencermountain** [comment]
hey @abushoeb yep, you can see emojis with:
```js
let doc=nlp('hello foobar 👍').match('#Emoji').out('array')
```

**Comment by abushoeb** [comment]
> hey @abushoeb yep, you can see emojis with:
> 
> ```js
> let doc=nlp('hello foobar 👍').match('#Emoji').out('array')
> ```

Great! Do we happen to have any Python wrapper for this?

**Comment by spencermountain** [comment]
hi Abu, not that I'm aware of. Let me know though, if you find a good solution for this.

If you need to stringify/reparse compromise objects, I recommend using the [export plugin](https://github.com/spencermountain/compromise/tree/master/plugins/export) for that, cheers.

**Comment by abushoeb** [comment]
Sure thing @spencermountain. Also, thanks for the pointer to the export plugin. 

Btw, do you have a small dataset/ test set for tweets containing emojis and their POS tags? I particularly checked both data and this [Unicode](https://github.com/spencermountain/compromise/blob/master/tests/unicode.test.js) test case but couldn't find the corresponding tags for emojis.
