### ISSUE TITLE
Expand contractions before applying tense transformations? (v7)

### ISSUE THREAD

**Issue by josephrocca** [nlp-compromise/compromise#310]
(Sorry if I'm reporting this as you're working on it - perhaps I should wait until v7 is released)

These two examples illustrate the problem:
```
nlp("I'm going to the shops").sentences().toPastTense().out("text") // --> "I'm went to the shops"
nlp("I am going to the shops").sentences().toPastTense().out("text") // --> "I was going to the shops"
```
Perhaps expand tense-based contractions (e.g. with words "am", "will") before processing (or something like that)?

**Edit:** Another thing: `nlp('london is calling').sentences().toNegative().out("text")` throws: `Uncaught TypeError: this.term.insertAfter is not a function` - guess this is still being worked on?

**Comment by spencermountain** [comment]
yes! 
yeah, this feature began as a bit of a joke, but functions as a good show-off example i figure.
there's a lot of logic to copy+paste from v6 for both these methods, and you're right - conjugation (nicely) plays into it ;) Let me get these two sentence methods into working-order, then ask you to kick up some dirt with it. Gimme a couple days.

**Comment by josephrocca** [comment]
Looking forward to it! •ᴗ•

**Comment by spencermountain** [comment]
agh! `i'm going` is [still not working](https://runkit.com/583f2a3dc534df0014136221/58c82cc35763290014d7b610)
rats. this'll be fixed in the next release. has top priority :sweat_smile: 
cheers

**Comment by spencermountain** [comment]
this one's fine now though:
```js
nlp('london is calling').sentences().toNegative().out()
```

**Comment by spencermountain** [comment]
hey, this works now too: :fireworks: 
```js
nlp('I am going to the shops').sentences().toPastTense().out()
// 'I went to the shops'
```
wee!
