### ISSUE TITLE
v7: issues with concatenation of toNegative and toPastTense

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#313]
Concatenating toNegative and toPastTense does not work. ie. toNegative is not applied.

toNegative() conjugate the verb to 3rd person singular even though the subject is first person singular ie. "I".

Both issues can be seen in this screenshot:
![image](https://cloud.githubusercontent.com/assets/2159624/22703214/457fcf44-ed5b-11e6-81d7-67593d612900.png)

**Comment by spencermountain** [comment]
thanks.
some of these bugs are known, and are why v7 is still unreleased. it may not make sense to file issues on the beta.
getting close.

**Comment by leoseccia** [comment]
ok, sorry for logging them...

**Comment by spencermountain** [comment]
hey leo, this one's fixed in `7.0.9`
cheers
https://github.com/nlp-compromise/compromise/blob/v7/test/unit/subset/sentence/tense.test.js#L47

**Comment by leoseccia** [comment]
Hello Spencer, Thank you for letting me know.
