### ISSUE TITLE
v7: Gerund as Noun

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#314]
In instances where the subject name (common or proper) is also a verb (in another context) then the subject is incorrectly marked as verb... I think if you have consecutive potential verbs then the first is most likely the subject and the second is the actual verb - unless the sentence is a question, in which case the order is reversed.

![image](https://cloud.githubusercontent.com/assets/2159624/22704492/c83b08d2-ed5f-11e6-96a9-b68b738f202d.png)

**Comment by spencermountain** [comment]
hey, just missed this one.

yeah, this is a good example. Reading here, even if it was the act of reading a book, should be a noun anyways. Right now `gerund` is a verb 'was reading quickly' - but it can also be a noun `reading is great`

**Comment by spencermountain** [comment]
hey leo, added support for a new #Activity tag, which is a noun.
![image](https://user-images.githubusercontent.com/399657/29743409-8316b344-8a5f-11e7-89e8-4fc1285bd111.png)

will be part of v11.
cheers
