### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by arjunmenon** [nlp-compromise/compromise#315]
Hey Man
Is it possible to include more entities in the dataset externally?
1. I would prefer to include datasets for maybe, listed companies, gazetteers, etc.
2. Write a rule to differentiate `blackberry` the company with `blackberry` the fruit.

Is it possible?

At present

```
const str="compare apple and microsoft"
nlp.text(str).organizations()
```
This would only return microsoft. If `apple` is replaced with `nike`, it would return both as organizations correctly.

**Comment by spencermountain** [comment]
hi Arjun, yeah this is possible - sorry the documentation is not so good right now.
you can pass-in your own lexicon of organizations like this:
https://runkit.com/583f2a3dc534df0014136221/589b2c88a4c6770013296ef4

in the next few weeks, [v7](https://github.com/nlp-compromise/compromise/tree/v7) will be released, which has better support for organizations.
cheers

**Comment by arjunmenon** [comment]
wohoo! That was cool!

About the custom rules to check. Like while parsing I create a rule to check order of certain words, their neighbors, etc to tell if the selected entity should be biased to a different category, then?

Also, otherwise if it could return ranking of entity label probabilities for a particular noun.

**Comment by spencermountain** [comment]
yeah, this type of thing is supported in v7, which I recommend using.
you can find specific templates with [.match()](https://github.com/nlp-compromise/compromise/wiki/Match-syntax) and tag them with `.tag()`

this is how it works:
https://runkit.com/583f2a3dc534df0014136221/589b2f70b360a1001488386d
theres not a lot of documentation for it yet

**Comment by arjunmenon** [comment]
That should get me started. Cool.
