### ISSUE TITLE
v7.0.18 not working in IE11

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#323]
Hello,

The library loads correctly in Chrome but it fails to load in IE11.

This is the error I get:
![image](https://cloud.githubusercontent.com/assets/2159624/23264738/5ad30808-f9da-11e6-9164-b24c2828d145.png)

![image](https://cloud.githubusercontent.com/assets/2159624/23264756/69bc95fa-f9da-11e6-984b-bbd9b467dd81.png)

Am I doing something wrong? BTW, this is using the normal version, the es6 version gives 2 errors...

**Comment by spencermountain** [comment]
hey leo, i've reproduced this on firefox34. taking a look now

**Comment by leoseccia** [comment]
I fixed this by adding:
![image](https://cloud.githubusercontent.com/assets/2159624/23268236/f6f485f4-f9e4-11e6-87b4-370038a3338a.png)

and now I have another one:
![image](https://cloud.githubusercontent.com/assets/2159624/23268250/014a49da-f9e5-11e6-8982-2eb9d71a3227.png)

**Comment by leoseccia** [comment]
Do you think this would help: https://github.com/es-shims/es5-shim?

**Comment by leoseccia** [comment]
It does... :)

This make it work:
	<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.5.7/es5-sham.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/json3/3.3.2/json3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-shim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.2/es6-sham.min.js"></script>
<script src="https://wzrd.in/standalone/es7-shim@latest"></script>
    <script src="../../builds/compromise.js"></script>

**Comment by spencermountain** [comment]
hey, tried all day to get ie8, but couldn't.
ie9+ though, works like a charm now `~7.0.28`
cheers!

**Comment by leoseccia** [comment]
I think IE9 and IE11 are the the main ones to worry about... IE8 would be the next one but it is only 3% of the browsing population (which probably clicked on IE by mistake anyway :) )

I like how this project is shaping up... Great work! Thank you!
