### ISSUE TITLE
Representing nested terms

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#324]
Currently dates are tagged in separate parts ie. 12th November 1981 is tagged this way:
```
[
	[
		{
			"text": "12th",
			"normal": "12th",
			"tags": {
				"Ordinal": true,
				"Value": true,
				"Date": true,
				"NumericValue": true
			}
		},
		{
			"text": "November",
			"normal": "november",
			"tags": {
				"TitleCase": true,
				"Month": true,
				"Date": true,
				"Singular": true,
				"Noun": true
			}
		},
		{
			"text": "1981",
			"normal": "1981",
			"tags": {
				"NumericValue": true,
				"Value": true,
				"Cardinal": true,
				"Date": true,
				"Year": true
			}
		}
	]
]
```
So each part of the date is tagged as "Date". I think it would be better if the tag was changed to "DatePart" and an additional lumped/combined term would be returned for the whole date and tagged as "Date".

Another related idea would be to have the concept of "LumpTerm", a "Term" which contains an ordered collection of Terms and no text of its own... This would be useful in instances other than Dates - cantractions, money (ie. $35) and the other lump-terms for example.

What do you think?

**Comment by spencermountain** [comment]
hey, yeah. it's a little weird isn't it.
I don't mind changing the name of the tag to something more clear. It'd be an easy, but breaking change.

the recursive lumpTerm idea is a cool one, which i have wanted to do, but is also pretty scary for the whole shebang - grabbing the values for example, would need to search through the nested lumpTerms, and build it's own lumpTerm or something. That's why i kept it flat, for now.

same principle for nounPhrase, verbPhrase, value+unit stuff - all of it.
:thinking:

**Comment by leoseccia** [comment]
I guess for date in particular, the consecutive dateparts could just be lumped together into one...

**Comment by spencermountain** [comment]
`.values()` wouldn't get the `1981` then!

**Comment by leoseccia** [comment]
My previous comment is rather vague... By date I mean actual (parse-able) dates (eg. 24th Jan 2000) not time qualifiers (eg. 24 years ago).

In that instance, would that really be an issue, given the context...? The consumer of the API would parse the returned term as a date and would be able to use the values within the dates accordingly.

**Comment by spencermountain** [comment]
if you or 'the consumer' ;) wants to parse the returned item as a date, that's what `.dates()` is for:
```js
nlp('feed the dog on 12th November 1981 and pet him too').dates().data()
[{
  text : '12th November 1981'
  ...
}]
```

**Comment by leoseccia** [comment]
Ah ok, that makes a lot of sense. However I dont get "text" when I run it on that very same sentence...
```
[
-{
-"punt": {
"direction": null,
"duration": { }
},
"section": null,
"relative": null,
-"date": {
"month": 10,
"date": null,
"weekday": null,
"year": 1981,
"knownDate": null,
"timeOfDay": null
}
}
]
```

Also another interesting result is that when I run it on "12th November 1981 is a bad day in history" i get a second seemingly empty entry ie.

```
[
-{
-"punt": {
"direction": null,
"duration": { }
},
"section": null,
"relative": null,
-"date": {
"month": 10,
"date": null,
"weekday": null,
"year": 1981,
"knownDate": null,
"timeOfDay": null
}
},
-{
-"punt": {
"direction": null,
"duration": { }
},
"section": null,
"relative": null,
-"date": {
"month": null,
"date": null,
"weekday": null,
"year": null,
"knownDate": null,
"timeOfDay": null
}
}
]
```

**Comment by leoseccia** [comment]
And on "12/1/1990" I get:
```
[
-{
-"punt": {
"direction": null,
"duration": { }
},
"section": null,
"relative": null,
-"date": {
"month": null,
"date": null,
"weekday": null,
"year": null,
"knownDate": null,
"timeOfDay": null
}
}
]
```

**Comment by spencermountain** [comment]
yikes!
definetly bugs.
i should roll-back that parsing stuff. it's not ready.
in the meantime, this should give you the text+ normal properties:
```js
.match('#Date+').data()
```
hey let me help you on slack. github issues are too stressy

**Comment by leoseccia** [comment]
ok great - thank you. When i go to: http://slack.compromise.cool I get a 502...

**Comment by leoseccia** [comment]
Hello Spencer,

'#Date+' is really good... When I use it with .out('json'), it groups the consecutive date terms together into arrays. It is very close to what I was suggesting ie. CombinedTerm

Thank you very much for your help!

Leo

**Comment by leoseccia** [comment]
Sorry this should probably be on a separate issue but it is related :)
'(#Person|#Date)' works as I would expect while '(#Person+|#Date+)' does not return anything at all.

**Comment by spencermountain** [comment]
Right. Maybe it should support that
(#Person|#Date)+ should work.  But if you dont want combinations of people and dates, you'll have to make two separate queries and do some kinda diff
