### ISSUE TITLE
"Tested" being marked as adjective instead of verb

### ISSUE THREAD

**Issue by leoseccia** [nlp-compromise/compromise#326]
The sentence "I tested" is being tagged like so:

```
[
[
{
"text": "I",
"normal": "i",
"tags": {
"Pronoun": true,
"Noun": true,
"Singular": true
}
},
{
"text": "tested",
"normal": "tested",
"tags": {
"Adjective": true
}
}
]
]
```

Tested is marked as an adjective instead of being a verb | past tense

**Comment by spencermountain** [comment]
hey leo, looks like this works now:
https://runkit.com/583f2a3dc534df0014136221/58c8279a3d42f900147f99c1
thanks!
