### ISSUE TITLE
Normalization always returns undefined

### ISSUE THREAD

**Issue by benhjames** [nlp-compromise/compromise#327]
Ahoy! Just wondering where the `normalize` method has gone on holiday to:

`nlp(' so... you like   DONUTS? have all the donuts in the WORLD!!!').normalize().out()`

gives:

`Cannot read property 'out' of undefined`

(v7.0.28 but seems to happen rather far back)

Cheers!

**Comment by spencermountain** [comment]
yikes!
thanks Ben, will check it out today

**Comment by spencermountain** [comment]
hey, this was a great find -  the method was just not returning `this` - which is a crazy oversight.
so thanks.
it's fixed on the dev branch, but is behind some work on dates for the next release. will keep it open till then
cheers!

**Comment by spencermountain** [comment]
hey ben, this is fixed in v8.0.2
https://runkit.com/583f2a3dc534df0014136221/58c81e80ee89c000150290d3
thanks for the heads-up!

**Comment by benhjames** [comment]
Awesome - thanks a lot! 🎉
