### ISSUE TITLE
Auxiliary

### ISSUE THREAD

**Issue by johnyesberg** [nlp-compromise/compromise#331]
Hi Spencer, thanks for your awesome work on compromise.
I tried to do a global search/replace from 'auxillary' to 'auxiliary', including renaming step 9, but many tests failed. 
I'd like to look into it further and send you a pull request when ready.
But not sure when I'll get there.

John

**Comment by spencermountain** [comment]
AHHHH

oh, that was just about the kindest way to tell me I made a humungous mistake. You must be a very patient person ;)
i'll take a look at this. It'll have to be v9, because it'd break the current api.

oooooooooof, thanks :heart:

**Comment by spencermountain** [comment]
fixed 'er in v9.0.0
thanks!!
