### ISSUE TITLE
Definitely in a sentence is recognised as noun

### ISSUE THREAD

**Issue by rnowosielski** [nlp-compromise/compromise#334]
I am not sure if I am doing something wrong here or not, but I came across a sentence

    Definitely accept the order!

that when treated with this module 

    nlp("Definitely accept the order!").nouns().data();

gets the following noun information

```
[
  {
    "article": "a",
    "singular": "definitely",
    "plural": "definitelies"
  },
  {
    "article": "an",
    "singular": "order",
    "plural": "orders"
  }
]
```

Maybe it is not 100% correctly in written English, but if this is a transcript of a conversation then this sort of phrase might be likely to occur.

**Comment by spencermountain** [comment]
yikes! thanks Rafal, will take a look

**Comment by spencermountain** [comment]
hey Rafal, got it.
will be an adverb now, as of `v8.2.0`
cheers
