### ISSUE TITLE
When is a name not a name?

### ISSUE THREAD

**Issue by allanyuill** [nlp-compromise/compromise#336]
"My name is Allan, my dog's name is Levi and the cat is named Cheeky."
The middle clause lables name as a verb and consequently doesn't identify "dog's" as possessive.

**Comment by spencermountain** [comment]
ah weird. thanks @allanyuill, that's a pretty nasty one.
worse is that the misinterpretation of 'name' made the preceding word `dog's`  misinterpreted to be 'dog is'.
i've removed 'name' from the verblist, so should be fixed in the next version, but eww...
great find!
