### ISSUE TITLE
toExclamation() greedy truncate

### ISSUE THREAD

**Issue by tmulroy** [nlp-compromise/compromise#347]
I'm getting some weird outputs when I'm using compromise with node v6.1.0 on the command line. 
For example, following the example on the v7 Upgrade welcome [page](https://github.com/nlp-compromise/compromise/wiki/v7-Upgrade,-welcome)

const nlp = require('compromise');
var r = nlp('Finally, the api is stable.');

r.nouns().toUpperCase();
'FINALLY, the API is stable. // r.out('text')

r.sentences().toExclamation();
'FINALL! the API is stabl!' // r.out('text')

Is this because of the node version I'm using or am I doing something stupid..

**Comment by tmulroy** [comment]
Apologies if this is the wrong place to ask questions!

**Comment by spencermountain** [comment]
agh! yikes
this looks like a sloppy bug on my part.
will take a look,
thanks!

**Comment by tmulroy** [comment]
Thank you for responding so quickly!

**Comment by spencermountain** [comment]
hey, got it.
will be fixed in `v8.2.0`
cheers

**Comment by tmulroy** [comment]
Thanks!
