### ISSUE TITLE
term-index as output

### ISSUE THREAD

**Issue by spencermountain** [nlp-compromise/compromise#350]
something like `.out('offset')` but with helpers for counting terms 
```js
var str=`I am the very model of a modern Major-General. I've information vegetable, animal, and mineral`
nlp(str).match('vegetable').out('index')
// [{ index:13, sentence:2, sentenceIndex:4}]
``

**Comment by owendall** [comment]
+1
This will be VERY useful.

**Comment by spencermountain** [comment]
got it. named it `.out('index')`
but renamed the output props to `term`, `sentence`, and `sentenceTerm` instead
`v8.1.0`!
lemme know

**Comment by owendall** [comment]
Great....Checking it out today...
