### ISSUE TITLE
Mr <name> <verb> categorised as a person with the name  Mr <name> <verb>

### ISSUE THREAD

**Issue by jranks123** [nlp-compromise/compromise#354]
A not so nice example, but the text "Mr Clinton raped" is being classified as male name with the name of "clinton raped". 

This is the body in question : 

"Just a week after his acquittal in the Senate impeachment trial, Bill Clinton faces a fresh scandal about his past sexual conduct after a former campaign worker alleged that he raped her 21 years ago. Juanita Broaddrick, who now runs a nursing-home business in Arkansas, told the Wall Street Journal that Mr Clinton raped her in the Camelot Hotel in Little Rock in 1978, when he was the state attorney-general. The newspaper reports that Mr Clinton persuaded Mrs Broaddrick to have coffee with him in her hotel room during a conference of nursing home administrators in 1978. She alleges that he then forced her on to the bed, where he held her down, bit her lips and raped her. When it was over, Mrs Broaddrick claims, Mr Clinton told her that she should not worry because he was sterile due to a bout of childhood mumps. Mrs Broaddrick is not directly quoted in the Journal's account of the alleged rape but in response to Mr Clinton's sterility claim she said: "As though that was the thing on my mind - I wasn't thinking about pregnancy or about anything. I felt paralysed and was starting to cry." She added: "This is the part that always stays in my mind - the way he put on his sunglasses. Then he looked at me and said 'You better put some ice on that'. Then he left." Norma Rogers, a friend of Mrs Broaddrick, told the Journal that she found the alleged victim in a state of shock. In reported speech, she is said to have alleged that Mrs Broaddrick's lips were discoloured and swollen to twice their normal size and the crotch of her tights was torn. "She just stayed on the bed and kept repeating 'I can't believe what happened'," Mrs Rogers said. Mrs Broaddrick's story has been the subject of rumours for years, and was widely circulated in 1992 when Mr Clinton was running for president. Until now she has refused to speak about the incident, and denied the story in an affidavit to lawyers for Paula Jones, who brought a sexual harassment case against Mr Clinton in 1994. Mrs Broaddrick's story surfaced in an American supermarket tabloid magazine in January, along with subsequently disproved claims that Mr Clinton had fathered the son of a black prostitute in Little Rock. On January 20 Mrs Broaddrick finally gave NBC television what is said to be her first media interview confirming the original rape allegation. Though scheduled for airing on January 29, the NBC interview has not yet been broadcast. NBC has described it as a "work in progress" - leading to rumours that the White House had put pressure on the network to withhold the story. The allegations come at a time when many of those involved in the past year's presidential crisis - including Monica Lewinsky, Linda Tripp and Gennifer Flowers - are telling their stories in books and media interviews. Mrs Broaddrick has also claimed that in 1991 she was called out of a meeting to discover Mr Clinton waiting for her. She said that he told her he wished to apologise and asked what he could do to make things up to her. Mrs Broaddrick said he could do nothing, and walked away. Shortly afterwards, Mr Clinton announced his presidential bid."

Calling nlp(body).people().data() results in 2 errors, "clinton raped" and "clinton's sterility"

**Comment by spencermountain** [comment]
ah, nice one. Yeah, it looks like the Mr honourific is being way too greedy. Hopefully two cases of the same bug. Will check it out today

**Comment by spencermountain** [comment]
hey Jonathan, got this squashed in v9.0.0:
```
let r = nlp('Mr. clinton raped and Mr. Clinton\'s sterility');
console.log(r.people().out('array'));
// [ 'mr clinton', 'mr clinton\'s' ]
```
you may also be pleased that it includes some pretty big performance improvements - something like ~40% faster.
Please let me know if you see anything else that's funky.
cheers
