### ISSUE TITLE
pass-in term metadata in lexicon

### ISSUE THREAD

**Issue by faizanahemad** [nlp-compromise/compromise#362]
Try `nlp("modulus").nouns().toSingular().out("text")` 
The result is "modulu", but actually modulus is singular and its plural is moduli
Try `nlp("moduli").nouns().toSingular().out("text")`
Result is "moduli" but it should be modulus.

Is there a way to specify to the engine these kind of rare/peculiar words? Like in a set of json document where each document would be structured as 
```
{
    "word":"modulus",
    "type":"noun",
    "plural":"moduli",
    "singular":"modulus"
    // In case word was of type verb then other fields like past-tense etc will be present
}

**Comment by spencermountain** [comment]
hi Faizan, thanks! Yeah, I'll fix that case today. I agree there should be a way to pass-in irregular forms in the api, and I like that format. That could work for verb conjugation too.
let me stew on one this for a little while.

**Comment by spencermountain** [comment]
hey @leoseccia you have any opinions on this idea?

**Comment by leoseccia** [comment]
Hello, 

In English, the plural form of words ending in -us is not straight forward... The general rule should be that if the singular ends in -us then the plural should be -i and all the (many) exceptions should go in data/nouns/irregular_plurals.js

Note: in some ways, the word "modulus" should actually be considered to be regular, as in it follows the main rule.

I'm not sure what would be expected for octopus, which has three plural forms: octopuses, octopi, and octopodes... 

There is a whole wikipedia article about these: https://en.wikipedia.org/wiki/Plural_form_of_words_ending_in_-us

From the point of view of passing data to the API, I have been thinking about this quite a lot. In the example that @faizanahemad provided, there is quite a bit of omittable info (ie. singular is the same as the word, the plural should not be considered irregular and type is actually a tag) however the idea is a good one.

I would describe it like this instead
{"modulus": {
   tags: ["Latin", "Noun"] //plural not included as it should be catered by the generic rule -us => -i
}, 
{"campus": {
   tags: ["Latin", "Noun"],
   plural: "campuses" //included here as it is irregular / an exception to the rule
},
{"campuses": {
   tags: ["Latin", "Noun"],
   singular: "campus" //included here as it is irregular / an exception to the rule
},
..etc..

I'm not sure whether the end in -i is a good enough sign of a noun being plural... What do you think?

On a side note, do you think there is any way to leverage on tries/dawg (or any other data structure) to make the lookup quicker on complex data type like the above? I can't think of a real way... I was toying with the idea of nested tries for a moment but my head started hurting very quickly.

**Comment by spencermountain** [comment]
man. exactly. That's exactly what I've been thinking about. craazy.

so the tries rn compress only a list of flat words. Maybe the solution involves getting them to hold an object somehow.

yeah, the applications include:
* pass-in flat lexicon with a tag - {word: 'Noun'}
* pass-in lexicon with meta-data - { word : { tag:'Noun', plural:'words' } }
* pass-in new tags with metadata - {tags: {Conductor: {parent: 'Person' }}}

just thinking aloud:
```js
{
  lexicon:{
    word:{
      meta : 'data'
    }
  },
  tags:{
    Conductor: {
      meta : 'data'
    }
  }
}
```

**Comment by spencermountain** [comment]
yeah leo, where i was going with your lexicon-as-trie idea was this:
```js
var nlp=require('compromise')
var myLexicon={blah:'whatever}
let shareableContext = nlp.pack(myLexicon)
...
nlp('say my name say my name, when no one is around you, say baby..', shareableContext)
```

**Comment by leoseccia** [comment]
yes, I like what you are saying and using the same object it would also be good to be able to pass regex/pseudo regex (as in containing nlp tags) rules somehow. ho and how about tag hierarchy?

**Comment by spencermountain** [comment]
yeah. so it becomes an all-in-one custom interpreter/parser thing. Love it

**Comment by leoseccia** [comment]
And on a side note (I am really side-tracking now), I love the nlp pseudo regex tag match but it would be great if we could make it work better and in harmony with real regex stuff, like XRegExp and the way it extends the POSIX...

**Comment by owendall** [comment]
:+1: on this and would like to add that being able to include more metadata that would allow for custom taxonomy-like relationships (synonyms, broader terms/parents) is key.

**Comment by spencermountain** [comment]
straight-up `nlp.addWords()` method is working on dev,

gonna look at adding a `nlp.addRegex()` for v11

right now it's pretty weird to do

**Comment by spencermountain** [comment]
hey guys, this stuff is deployed on v11:
```
nlp.addWords()
nlp.addTags()
nlp.addRegex()
nlp.addPatterns()
nlp.addPlurals()
nlp.addConjugations()
//or just combine them in:
nlp.plugin()
```
please check it out,
https://github.com/nlp-compromise/compromise/wiki/Plugins
https://github.com/nlp-compromise/compromise-plugin
cheers!
