### ISSUE TITLE
Cannot read property 'Copula' of undefined when using .conjugate() on specific string

### ISSUE THREAD

**Issue by mattjennings** [nlp-compromise/compromise#364]
`nlp('come, perhaps').verbs().conjugate()`

The above code will crash with an error of 'Cannot read property 'Copula' of undefined'.

'my take on' will also cause the same error.

**Comment by spencermountain** [comment]
yikes!
thanks Matt, will check it out today.

**Comment by spencermountain** [comment]
hey, got these two examples fixed in `v10.0.1`, 
```js
console.log(nlp('come, perhaps').verbs().conjugate());
/* [ { PastTense: 'came',
    PresentTense: 'comes',
    Infinitive: 'come',
    Gerund: 'coming',
    Actor: 'comer',
    Participle: 'come',
    FutureTense: 'will come' } ] */
console.log(nlp('my take on').verbs().conjugate());
//[]
```
but there's some pretty ugly stuff going on there, so please let me know if you find something else.
cheers!

**Comment by spencermountain** [comment]
for the morbid, 'take on' was being interpreted as a verb - "take on an enemy" but then error-corrected back to a noun because of "my take" - but the particle, 'on' was being left dangling as a verb. not good! :parasol_on_ground:

**Comment by mattjennings** [comment]
Awesome! Thanks for the quick response. I'll let you know if anything else comes up.
