### ISSUE TITLE
Happy compromise user :)

### ISSUE THREAD

**Issue by josephrocca** [nlp-compromise/compromise#368]
Hey @spencermountain, [way back](https://github.com/nlp-compromise/compromise/issues/311#issuecomment-275695372) I told you I'd let you know when my compromise-powered project was finally released. After a few development delays I've finally released it:

https://perchance.org

It's an online platform thing for creating random text generators. Thanks for all the work you put into this lib! :)

**Comment by spencermountain** [comment]
beauty! nice one!
