### ISSUE TITLE
Add other region name..

### ISSUE THREAD

**Issue by andikas** [nlp-compromise/compromise#370]
Hi @spencermountain and all,
need some advice or suggestion. I stuck on this for hours.

I want to have a name extraction from a sentence. 
Eg: james and tony brian is havng lunch right now.
result: James,tony brian.
I have this result as expected.

The problem is, there're some name that the ''compromise" couldn't detect.
Eg: Mark hughes
result: hughes (the system can't detect mark)

I want need help about:
1. where do you guys save the DB of name, is there any way I could review or add some new name (e.g asia's name (India's name or wife/husband))

**Comment by spencermountain** [comment]
hi andikas! Good find.
Yeah, you can force compromise to interpret 'mark' (or anything) by [adding them to the lexicon](https://github.com/nlp-compromise/compromise/wiki/Lexicon#adding-words).
```
var lexicon = {
  mark: 'Person'
};
var r = nlp('he is mark hughes', lexicon).debug();
```
that should help for now, but I'm gonna leave this open, because 'mark' shouldn't be a verb, especially beside a lastName! sounds like a bug.
thanks!

**Comment by andikas** [comment]
Hi @spencermountain ,
Thank you for your quick respond.

so, we can't add a new firstname or lastname right now?
because I'm doing a project right now, and that system should be able to detect people name in a sentence.
I mean, if I use that array in lexicon, imho, that's not the best solution. there would be too many name i should describe in my script array.
is there any suggestion how can I achieve this with database or something neater??

**Comment by spencermountain** [comment]
hi, yes you can tag anything as a first name, or last name, or anything you'd like:
```js
var lexicon = {
  mark: 'FirstName',
  amber:'FemaleName',
  john:'MaleName',
  hughes:'LastName',
  foobar:'AnytagYouWant',
  'multi word term':'Person'
};
var r = nlp('he is mark hughes', lexicon).debug();
```
cheers

**Comment by spencermountain** [comment]
hey Andikas, this example works now, without needing a lexicon:
```js
var arr = nlp('he is mark hughes').people().out('array');
console.log(arr);
// [ 'mark hughes' ]
```
cheers

**Comment by andikas** [comment]
Hey Spencermountain,

Sorry for the late respond and Thanks for all your hard work.
I have tested it, and mark works as a firstname right now.
And for adding other name, I'll go with array although it will create a very long array.
lol

Thanks again for all your help.
