### ISSUE TITLE
Question: Is there a way to use this to convert sentences into SQL queries?

### ISSUE THREAD

**Issue by rajaraodv** [nlp-compromise/compromise#374]
I have access to DB and was wondering if there a way to use this to convert sentences into SQL queries? Or, are there any tools that we can use on top of this?

**Comment by spencermountain** [comment]
hi Raja, that's a neat idea.
i haven't seen anything that can do this. It would be pretty hard, but here's how I would go about doing it:
https://runkit.com/spencermountain/5930259f5fbe2100112f611f
cheers

**Comment by rajaraodv** [comment]
@spencermountain thanks! That's a very interesting approach
