### ISSUE TITLE
Question: Is it possible to auto-complete (i.e. use regex for keywords)?

### ISSUE THREAD

**Issue by rajaraodv** [nlp-compromise/compromise#375]
I need to show auto-complete suggestions as the user types. So if the user is typing "Piz" or "Pizz", I need to recognize it as a potential keyword for Pizza and suggest "Pizza". How to go about doing it?

**Comment by spencermountain** [comment]
hey Raja, if the input is already parsed, you can get the final term with this:
```
doc=nlp('i ate som pizz')
doc.last().lastTerm().out('normal')
//'pizz'
```
you can lookup your keywords with that.
it's harder though, because a user can re-type terms from the middle.
that's a bit trickier
