### ISSUE TITLE
Question: Is it possible to distinguish b/w two keywords with same tag?

### ISSUE THREAD

**Issue by rajaraodv** [nlp-compromise/compromise#376]
Sentence: "Book a flight from SFO to JFK".  
Sentence2: "Book a flight to JFK from SFO"

Based on my tagging, I'll get SFO, JFK as airportCodes. But I'd like to tag them as "startingAirportCode" and "endingAirportCode" irrespective of where they are located. How to achieve that?

**Comment by spencermountain** [comment]
hey raja,
```js
doc.match('#AirportCode to @AirportCode').tag('#StartingAirportCode . #EndingAirportCode')
```
that should do the trick
cheers
