### ISSUE TITLE
Peoples and Places not recognized

### ISSUE THREAD

**Issue by SankarshanDudhate** [nlp-compromise/compromise#378]
Hi guys,

   When I'm looking for People and Places in a string, many of the names aren't recognised. 

e.g. Richard Nixon classifies as a Person. 
Prathmesh Patil doesn't. But Richard Patil does.

 Patil is a common Last Name in India.

Another one
 e.g. Mumbai gets classified as a place. But Latur doesn't.

Latur is my hometown.

So, what's going on here ? Is there anything we can do about it ?

  Regards,
Sankarshan

**Comment by spencermountain** [comment]
hi Sankarshan, thanks.
yeah, we had to make some 'compromises' to keep the library small, and some names + places didn't make the cut. I'd specifically like the library to do a better job [at indian names](https://github.com/nlp-compromise/compromise/issues/169), but gotten very far on that yet.
in the meantime, you can set anything you want via the lexicon:
```js
var myWords={
  'latur':'City'
}
var r = nlp('Latur is nice', myWords).places().length
//1
```
btw, Latur looks really nice.
cheers

**Comment by SankarshanDudhate** [comment]
Thanks a lot for the answer Spencer. Lexicon does thr job.

Cheers
