### ISSUE TITLE
Lexicon Enhancement Discussion

### ISSUE THREAD

**Issue by owendall** [nlp-compromise/compromise#383]
This is just a start to gather use-cases and ideas from other domains.

**Comment by owendall** [comment]
# Incorporate basic taxonomy ideas when creating new Lexicon entities: So, new attributes would include:

Trying not to be as academic as WordNet:
https://www.slideshare.net/govindraj15/wordnet-27805299?next_slideshow=1

## Start with Nouns for what I think would be the first big win:

Allow 

1.  BT: "Broader Term"
2. SN: "Synonym" 

We would get:

3. NT: "Narrower Term"  from the definition of lowest-level items.

```javascript
{
"lexicon":
 [ 
  {
  "id":1001,
  "text":"dog",
  "context":"TBD",
  "pos":"noun",
  "bt":"mammal",
  "sn":["canine","pooch","hound"]
  },
  {
   "id":1001,
   "text":"spaniel",
   "context":"TBD",
   "pos":"noun",
   "bt":"dog",
   "sn":""
   },
....
 ]
}
```

**Comment by owendall** [comment]
We also need to expand the hierarchy used within compromise to allow for things like the hierarchy of organizations (small business -> business -> for profit organization -> organiztion.

**Comment by owendall** [comment]
So, how do we allow for a more dynamic "matching" such that we could match only on "Amino Acids"?  In this case we will assume we have already added to our lexicon the 20 amino acids before we execute this example (excuse the crude code.):

``` javascript
  var text = "I have heard that tryptophan can help you sleep"
  // I want to include anywhere that either the text "Amino Acid" (e.g, "self") or the narrower terms ("nt") are found
  var results = nlp(text) .match({"noun":"Amino Acid", "include":["self","nt"]}).out("list");
// results = "tryptophan"

![image](https://user-images.githubusercontent.com/10927/27011596-b13c3b54-4e8c-11e7-8cf0-4927fd53320e.png)

**Comment by owendall** [comment]
I guess this just a more generic form of your custom-pos-tagging:

https://nlp-expo.firebaseapp.com/expo/custom-pos-tagging-161281

**Comment by spencermountain** [comment]
yeah, there's a lot of great ideas to unpack here.

1) broaderTerm/synonyms
what are you using this for, if you don't mind me asking? I have a big place in my heart for [this idea](https://github.com/nlp-compromise/compromise/issues/304) still - how do you feel about that 1-to-1 style?

2) **non-text matches**. Love this. If you want to match 'proline' only when it's a noun, right now you have to do two matches. We should totally support 'advanced-style syntax', for multiple-matches at once. There's potentially some tricky stuff that could come up, with some short-cuts I've made.

:smile: 'trying not to be as academic as wordnet' is basically what i'll put on my gravestone :smile:

**Comment by owendall** [comment]
@spencermountain Can we continue discussion with this?

**Comment by spencermountain** [comment]
yeah, lemme get persistent lexicon-changes first, which is hard, and will be a major, breaking version, so we may wanna include some other stuff in it.

i really like your non-text-based matches idea too, like 
```
doc.match([{text:'proline', tag:'Noun'}])
```
so ideally that happens right after/beside

**Comment by spencermountain** [comment]
so the ordering is 
1) nlp.addWords()
2) doc.match(Object)
3) support of synonyms+hierarchies

**Comment by spencermountain** [comment]
just cleaning up tasks, so gonna close this.
a lot of the plugin work is supported in v11. 
`.match(json)` is still a good idea but doesn't sound like a priority rn

https://nlp-compromise.github.io/compromise-plugin/
more details in here - (https://github.com/nlp-compromise/compromise/wiki/Plugins)
