### ISSUE TITLE
Apostrophe creates an extra word

### ISSUE THREAD

**Issue by KingsleyMartin** [nlp-compromise/compromise#384]
In version 10.0.0 the text below creates an array of 68 elements. In version 10.0.5, it creates 69 elements. The apostrophe in “Provider's” creates two words: “Provider” and “is.” Interestingly, the same issue does not occur with "Recipient's," which appears later in the sentence.
 
Upon the Provider's request, the Recipient and its Representatives will promptly deliver to the Provider, or at the Recipient's election, destroy any of Provider's Confidential Information (and all copies thereof) obtained or possessed by the Recipient or any of its Representatives; provided, however, that, in the event Recipient and its Representatives elect to destroy such Confidential Information, the Recipient shall deliver to Provider a certificate confirming such destruction.

**Comment by spencermountain** [comment]
hey kingsley! yuck, thanks. yeah, the posessive v. contraction method is supposed to be a bit smarter than that.
i'll check it out.

**Comment by KingsleyMartin** [comment]
Hi, Spence. Great work on compromise!
And, the apostrophe issue already fixed! Thanks.
