### ISSUE TITLE
Justeson and Katz patterns for .nouns()

### ISSUE THREAD

**Issue by owendall** [nlp-compromise/compromise#387]
"Take the longest sequence that fits one of the following parts-of-speech patterns:"
AN
NN
AAN
ANN
NAN
NNN
NPN

N = Noun
A = Adjective
P = Preposition

This is something discussed by Manning and Schutze as the “Justeson and Katz Filter" from their 1995 paper. It was focused on how to extract technical terminology.

**Comment by owendall** [comment]
@spencermountain I started playing with something like this:
```javascript
         results = nlp(parsingText).match("#Noun #Preposition #Noun #Adjective? #Noun?").out('array')
```

**Comment by owendall** [comment]
But I would need to go through all permutations.  Something internal would be more performant. This is an example of a test I did on a small 200 document list.

[noun-phrase-test-200-docs.txt](https://github.com/nlp-compromise/compromise/files/1095112/noun-phrase-test-200-docs.txt)
Here is the source:
[nifa-data-all-200.txt](https://github.com/nlp-compromise/compromise/files/1095116/nifa-data-all-200.txt)
(Parsed only the 10th field)

**Comment by spencermountain** [comment]
heyyy, i did some of this yesterday, you may be pleased. I didn't copy their thing directly, but did lift a bunch of their examples/thinking.

https://github.com/nlp-compromise/compromise/blob/master/test/unit/subset/noun/nounPhrase.test.js

lemme know if you see anything weird/bad
cheers
