### ISSUE TITLE
EndPunctuation regex fails

### ISSUE THREAD

**Issue by sebilasse** [nlp-compromise/compromise#397]
The `EndPunctuation`‘s regex `endPunct` does not allow a space : 
`/([a-z])([,:;\/.(\.\.\.)\!\?]+)$/i;` in https://github.com/nlp-compromise/compromise/blob/df050d5be8994f4124274f3bfc84e4ff61814e83/src/term/methods/punctuation.js

That means for example "Who is Boris Becker ?" has _no_ `EndPunctuation` and is _not_ detected as a question because when I look at the `questions` subset, questions must have a `?` as `EndPunctuation`  : 
```
let list = r.list.filter(ts => {
    return ts.last().endPunctuation() === '?';
});
```

**Comment by sebilasse** [comment]
Also an idea to detect questions for texts without punctuation, e.g. 

"who is boris becker"

> if no `endPunctuation`
```js
var isQuestion = [
    'who (#Person+|#Organization+|#AtMention+)',
    'where (#Person+|#Place+|#Organization+)$',
    'when (#Date|#Pronoun+|#Noun+|#Singular+|#Plural+)$',
    '^(how|#QuestionWord) (#Pronoun|#Noun|#Singular|#Plural|#Gerund)$', //3
    '^(how|#QuestionWord) (#Copula|#Gerund|#PresentTense|#PastTense) * !#Infinitive', //4
    '^(#Modal|#PresentTense|#PastTense) (#Determiner)? (#Copula|#Pronoun|#Noun|#Singular|#Plural|#Gerund) * !#Infinitive$',
    '^(#Adverb|#Pronoun) (#Modal|#PresentTense|#PastTense) * !#Infinitive$'
].reduce((res, rule, i) => {
    if (!!txt.match(rule).out().length) { matched.push(i) }
    return !!res || !!txt.match(rule).out().length
}, false)
```

**Comment by spencermountain** [comment]
yikes! yeah. I really like both of these ideas Sebastian (and nice to see you back again!)

yeah, `boris becker ?` should not be three words. That's bad. I'm not sure where the best place to fix it is. the `sentence_parser` needs to be sensitive about false-positives. This is a good case where it should be smarter.

Yeah, the absolute best situation regarding isQuestion, would be when the text gets parsed, each Sentence class gets parsed into either `Statement` or `Question` (or anything else?). This would additionally be helpful for things like `.toNegative()` and stuff, where that logic really oughta be more clever.

working on the new lexicon stuff in the `newAPI` branch rn, but would like to address this stuff soon, PRs welcome!

**Comment by sebilasse** [comment]
Ok.
Not sure, did not dive into the code but will do when there is more time ...
[everybody feel invited https://indieweb.org/2017/Dortmund 🔥 CAMPFIRE - Festival for journalism]

Some other findings about `questions` :
It does not detect them when they end in a number or another punctuation, e.g.
"What album put The Beatles on the cover of Time in 1967?"
"Where is Procter & Gamble headquartered in the U.S.?"
These come from https://github.com/superscriptjs/qtypes/blob/master/data/500q.txt

What I did this night was to "rewrite" https://github.com/superscriptjs/qtypes for compromise.
Did it because I needed the question intent for an indieweb bot.
But could imagine that we could simply use silentrobs' other rules to detect the yet undetected questions.
Just do not know how to fix the space before the `?`.
For now correcting it per sentence and let nlp do the sentence again - the nuclear option ;)

**Comment by sebilasse** [comment]
The word `How` is currently not detected as a `Question word` (?)

**Comment by sebilasse** [comment]
Found it out - the regex `endPunct` should be 
`var endPunct = /(?:([,:;\/.(...)!?])|\s)+?$/i;` to allow for spaces and combinations as in
"Is Trump a fool or the president of U.S. ?"

**Comment by sebilasse** [comment]
Can anybody test things like
"How much would it cost to purchase a 2-foot-square party tent , with sides , ?"
```
{ text: 'sides',
    normal: 'sides',
    tags: [ 'PresentTense', 'Verb', 'VerbPhrase' ] },
  { text: ',', normal: ',', tags: [] },
  { text: '??', normal: '?', tags: [] } ]
```
Why does the last tag have "??" as text - there is just one "?"

**Comment by spencermountain** [comment]
hey, i think these are both still busted, no?
```js
let doc = nlp('boris becker ? he is nice.')
let doc = nlp('Is Trump the president of U.S. ? i guess so')
```

**Comment by spencermountain** [comment]
hey, i got the `boris becker ?` one working, but couldn't get `U.S. ?` working.
can you add a test for that regex you added?
cheers

**Comment by sebilasse** [comment]
@spencermountain 
I see, unfortunately there is no real "lookahead" in JS regexes.
The regex will always only match the last 2 characters as you can see in https://regex101.com when you select "Javascript" in the left/burger menu ...

So it might not be possible to handle everything it in a single regex. 
The sticky flag coming to ES2015 might help us in the future.
What I unfortunately do not understand for now is the overall handling of the endPunctuation ...
Try to have a look later.

**Comment by spencermountain** [comment]
hey, just cleaning up tasks, gonna close this.
`nlp(' U.S. ? ')` is a edge-case i'm willing to let us waffle on for now.
cheers!
