### ISSUE TITLE
QuestionWord

### ISSUE THREAD

**Issue by sebilasse** [nlp-compromise/compromise#399]
Trying to find out under what circumstances the words `how` and `which` are not detected as `QuestionWord`

Tested 5000 questions so far (did already some corrections described in https://github.com/nlp-compromise/compromise/issues/397). 

For `how` it was not detected with 'many/much' suffix or a plain verb 
[but I _could_ do `(how|#QuestionWord)` and 
regarding `which` it had no `QuestionWord` for the following which :

```
ERROR TYPE-- NO TYPE  WH Which city has the oldest relationship as a sister city with Los Angeles ?
ERROR TYPE-- NO TYPE  WH In which year was New Zealand excluded from the ANZUS alliance ?
ERROR TYPE-- NO TYPE  WH Which company created the Internet browser Mosaic ?
ERROR TYPE-- NO TYPE  WH Which Bloom County resident wreaks havoc with a computer ?
ERROR TYPE-- NO TYPE  WH Which Ventura County police department seized the largest cocaine shipment in it 's history ?
```

**Comment by spencermountain** [comment]
hey Sebastian, wanna join the [slack group](http://slack.compromise.cool/)?
there you'll find a ton of people who are interested in this work. 
It would be wicked if you'd make a PR for this work, just remember to make em small - and any API changes should be discussed!
would be great to get this questionWord disambiguation stuff in. 
cheers

**Comment by sebilasse** [comment]
@spencermountain ok, i will do so later ...
The code is much more modular now and the custom lexica idea is awesome !

Can we first discuss the fix for "how" and "which" - found it out -
please see [tagger/corrections/index.js](https://github.com/nlp-compromise/compromise/blob/2978cd424fee0b522af5903043fc0d2101eeb7ee/src/tagger/corrections/index.js) - line 114 :
```
//the word 'how'
ts.match('how (#Copula|#Modal|#PastTense)').term(0).tag('QuestionWord', 'how-question');
```
how about changing it to 
```
//the word 'how'
ts.match('how (#Determiner|#Copula|#Modal|#PastTense)').term(0).tag('QuestionWord', 'how-question');
//the word 'which'
!ts.match('which . (#Noun)+ #Pronoun').list.length &&
ts.match('which').term(0).tag('QuestionWord', 'which-question');
```

that would mean that

- "`how` much", "`how` many" etc. is covered
- it is not as in "`which` color temperature you use depends on" then `which` _is_ a question word
  (no matter if it is an 'indirective question word' because that is also a question word)

---
There is one general problem now :
The old version did detected `nouns` that are also `verbs`
like "state", "rule", "tie" ...
Those are always recognized as verbs (?)
Let's change the above example and change it to  "`which` color tie you use depends on"
then tie would be detected as a Verb ...

**Comment by sebilasse** [comment]
> would be great to get this questionWord disambiguation stuff in.
Yep, that is only a small step then.
Worked on it until today : detect, type and intent is now 99% correct if I do the test questions (better than the original now ;)

@spencermountain 
I would do three PRs today to get punctuation fully working:
1) The above for `how` and `which`
2) The endPunctuation described in https://github.com/nlp-compromise/compromise/issues/397#issuecomment-323472211
3) The "questionWord disambiguation stuff"

Two questions :
- Are the current test results tracked somewhere?
- Do I also need to include the builds in PR?

**Comment by spencermountain** [comment]
cool! yeah `dev` branch, and try to keep the same number of failing tests as there are already ;)
ooh - you can add the results [here!](https://github.com/nlp-compromise/compromise/wiki/Accuracy)

**Comment by sebilasse** [comment]
Regarding tests the end punctuation suggestion somehow fails - need to work on it
```
append:
      ✖ append-with-without-period
      ✖ append-with-exclamations
      ✖ multiple-word-append

setPunctuation:
      ✖ toexclamation-change
```

**Comment by spencermountain** [comment]
hey, i started looking at handling questions without question marks, wanna help?
it's hard.
https://github.com/nlp-compromise/compromise/blob/02e9e8ac41b9fa155d07679e3f5c2d4382598357/test/unit/subset/sentence/question.test.js#L44

**Comment by sebilasse** [comment]
Yes, no problem 
posted the `match` tests in https://github.com/nlp-compromise/compromise/issues/397 and just worked on it !

What I am currently doing :
1. Check if there is just one sentence
2. Run the `match` thing below

so if there is just one sentence

```js
function uq(str) {
  var doc = nlp(str);
  var ep = doc.list[0].terms[doc.list[0].terms.length-1].endPunctuation();
  if (['.','!'].indexOf(ep) > -1 ) {
    return false
  }
  var allQW = (qw) => {
    if (typeof qw === 'string') {
      return `${s}${s}'s|${s}'re|${s}'d|${s}'ll`
    }
    return `#QuestionWord #Contraction${(qw === true) ? '' : '?'}`;
  }
  var blabla = '(#Conjunction|#Preposition|#Adverb)?';
  return [
    `^${blabla} ${allQW('how')} (#Adjective|#Copula|#Modal|#PastTense)`,
    `^${blabla} (what|which) #Noun`,
    `${allQW('who')} (#Person+|#Organization+|#AtMention+)`,
    `${allQW('where')} (#Person+|#Place+|#Organization+)$`,
    `${allQW('when')} (#Date|#Pronoun+|#Noun+|#Singular+|#Plural+)$`,
    `${allQW()} #Modal`,
    `${allQW()} (#Pronoun|#Noun|#Singular|#Plural|#Gerund)$`,
    `${allQW()} (#Copula|#Gerund) * !#Infinitive`,
    `^${blabla} ${allQW(true)} #Modal? #Pronoun #Verb+`,
    `^${blabla} (#Modal|#PresentTense|#PastTense) (#Determiner)?
      (#Copula|#Pronoun|#Noun|#Singular|#Plural|#Gerund) * !#Infinitive$`,
    `^${blabla} (#Adverb|#Pronoun) (#Modal|#PresentTense|#PastTense) * !#Infinitive$`
  ].reduce((res, rule, i) => {
    return !!res || !!doc.match(rule).found
  }, false)
}

function uqLog(sentence) {
  console.log(uq(sentence) ? 'QUESTION' : 'STATEMENT', sentence)
}

console.log('questions:');
var q = [
  'which party was it',
  'which day was it',
  'but who did you go with',
  'what time did you show up',
  `why'd you come so early`,
  `when'll you show up`,
  `where'd you go afterwards`,
  `is it fun`,
  `was it fun`,
  `did you think it was fun`,
  `so, is it fun`,
  `so, where'd you go`,
  `if you said so, why are you upset`,
  `does wayne gretsky skate`
];
q.forEach(uqLog);

console.log('statements:');
var s = [
  "the thing is, it isn't cool",
  'does the orchestra respond, no.',
  "where there is smoke, there's fire",
  'does the orchestra ever suck!',
  'when i go fishing i eat plankton'
  // "how he got out of his cage, i don't know",
  // 'who else but the rolling stones...',
  // "what i'd like to say is, thanks for the fish"
]
s.forEach(uqLog);
```

`function uq` _should_ answer if it is a 

> questions without question marks

As you can see in the one failing I need to work on VerbPhrases with nouns ...

**Comment by sebilasse** [comment]
additionally (this is very opinionated)
```TypeScript
const isDescribeQuestion = doc.match('^give a reason').found ||
        doc.match('^(describe|define|name) !#Modal').found;
```

**Comment by spencermountain** [comment]
hey, that's pretty neat. It's awesome to see you mastering the match syntax. lemme know if you have any ideas for making it clearer, or smarter/faster/whatever.

one thing, i think `.match()` will find anything in contraction-form, so 
```js
allQW('who')
allQW('where')
```  
can just be:
```js
"(who|where) (is|will|have)? "
``` 
lemme know if I'm wrong, i may be ;)

hey, if wanted to commit some kinda performance test like this, that's cool. If a unit test was something that should always pass, i figure a [stress test](https://github.com/nlp-compromise/compromise/tree/master/test/stress/question-forms) is something that you run and it tells you how well it does on something...
up to you!

**Comment by spencermountain** [comment]
if we removed all the question marks from that dataset, how well does it do?
maybe 50% detection??

--- hey, just as i'm thnking about it, it maybe also be cool to look for false-positives by running this through a big dataset and looking for sentences we thing are questions, but that have a period?
