### ISSUE TITLE
Nouns that can be Verbs

### ISSUE THREAD

**Issue by sebilasse** [nlp-compromise/compromise#401]
When I tested the 5000 questions the POS was fine except for some Nouns that can be Verbs as well.

Findings:

On what T.V. show could Tom Terrific be found ?
`> show should be #Noun and not #Verb`

What sprawling U.S. state boasts the most airports ?
What U.S. state lived under six flags ?
What U.S. state has an element named for it ?
`> state should be #Noun and not #Verb`

What ocean is the largest in the world ?
`> ocean should be #Noun and not #Adjective`

I _guess_ it helps for those Nouns like
`state, rate, show, address, color, rule, tie` (could also be verbs) or
`ocean, medium, equivalent` (could also be adjectives) to **add them to the lexicon** [`Singulars`](https://github.com/nlp-compromise/compromise/blob/master/src/lexicon/compressed/data/nouns/singulars.js) ...

_the only few other findings_ 
What is the largest snake in the world ?
`> largest should be #Adjective and not #Noun`
to [`irreg. Adjectives -> toSuperlative`](https://github.com/nlp-compromise/compromise/blob/master/src/lexicon/uncompressed/irregularAdjectives.js)

What causes the body to shiver in cold temperatures ?
`shiver should be #Verb and not #Noun`

---
What contracts United States ?
What abridges United States ?
What abbreviates United States ?

Such `Verbs` are always `Nouns` but they should not ...
Did not dive into the rules yet but maybe a `QuestionWord` should be treated like the word `it` ...

**Comment by spencermountain** [comment]
agh, great finds @redaktor!
* [] tv *show*
* [] U.S. *state*
* [] *ocean*
* [] is the *largest* 
* [] to *shiver*
lets get em!

**Comment by Froren** [comment]
@spencermountain Took a stab at the last 3 with [this PR](https://github.com/nlp-compromise/compromise/pull/419/files)

**Comment by spencermountain** [comment]
hey, got through these, they were great.
thx Sebastian - `^11.2.3`
