### ISSUE TITLE
Crash in Firefox

### ISSUE THREAD

**Issue by DirkStevens** [nlp-compromise/compromise#402]
Hello,

Using compromise in Firefox crashes:
**TypeError: all[k].push is not a function[Learn More]  line 684:11**

  var all = {};                                                                                                        // 671
  Object.keys(obj).forEach(function (cat) {                                                                            // 672
    var arr = unpack(obj[cat]);                                                                                        // 673
    //special case, for botched-boolean                                                                                // 674
    if (cat === 'true') {                                                                                              // 675
      cat = true;                                                                                                      // 676
    }                                                                                                                  // 677
    for (var i = 0; i < arr.length; i++) {                                                                             // 678
      var k = arr[i];                                                                                                  // 679
      if (all[k] !== undefined) {                                                                                      // 680
        if (typeof all[k] === 'string') {                                                                              // 681
          all[k] = [all[k], cat];                                                                                      // 682
        } else {                                                                                                       // 683
          **all[k].push(cat);                                                                                            // 684**
        }                                                                                                              // 685
      } else {                                                                                                         // 686
        all[k] = cat;                                                                                                  // 687
      }                                                                                                                // 688
    }                                                                                                                  // 689
  });                                                                                                                  // 690
  return all;

**Comment by sebilasse** [comment]
This seems to be the place where it unpacks the lexica.
Do you use a custom lexicon?
Try to change line 683 to
`} else if Array.isArray(all[k]) {`

**Comment by spencermountain** [comment]
ahh yikes!
thanks Dirk, will roll-out a hotfix today.

**Comment by DirkStevens** [comment]
@sebilasse and @spencermountain 
Wow, thanks for looking into this so fast, that's great!!

**Comment by spencermountain** [comment]
hey @DirkStevens, can you share somehow the lexicon you used to trigger this?
if it's proprietary, or too big, just share the part that triggers it?
it may be sensitive to numbers, unicode, true/false, etc.

**Comment by DirkStevens** [comment]
Hello @spencermountain, 

What do you mean with the lexicon?

Here's more information that I got by breaking right before the crash:
![screen shot 2017-08-22 at 09 55 03](https://user-images.githubusercontent.com/1837524/29554595-04556fc4-8720-11e7-8d32-24694b093959.png)
[all.txt](https://github.com/nlp-compromise/compromise/files/1241213/all.txt)
[arr.txt](https://github.com/nlp-compromise/compromise/files/1241214/arr.txt)
[arguments.txt](https://github.com/nlp-compromise/compromise/files/1241215/arguments.txt)

**Comment by sebilasse** [comment]
@DirkStevens I think he means what I asked too : 

Do you only use the default Lexicon or did you add your [own Lexicon](https://github.com/nlp-compromise/compromise/wiki/Lexicon) ?

**Comment by DirkStevens** [comment]
@sebilasse I use the default Lexicon.

My code performs text analysis with ngrams to find often occurring phrases, however that code is not executed prior to the crash.

**Comment by spencermountain** [comment]
ahhh `'watch'`, a reserved word in firefox, but not the others.
nice bug! 🥇 
holy smokes, i can't believe this landed on production!

**Comment by sebilasse** [comment]
@spencermountain just btw: TypeScript is what makes me happy ;) I am a bit confused by the PR view. It lists all unmerged changes (not only by me [?])

**Comment by spencermountain** [comment]
k, fixed in `10.7.2`. 
lemme know if you see anything fishy goin on
thanks you two!

**Comment by DirkStevens** [comment]
Works!  Thanks so much @sebilasse and @spencermountain
