### ISSUE TITLE
Past tense of revoke should be revoked

### ISSUE THREAD

**Issue by daedalus28** [nlp-compromise/compromise#404]
The past tense of `revoke` is coming out as `revoke`, but should be `revoked`.

Here's what I ran in [runkit](https://npm.runkit.com/compromise):

```js
var nlp = require('compromise')
let pastTense = verb => nlp(verb).sentences(0).toPastTense().out('text')
pastTense('revoke')
```

Also here is a somewhat random internet source to back up my claim that `revoked` is correct English in case you have doubts: https://en.wiktionary.org/wiki/revoked#English

**Comment by spencermountain** [comment]
... like 'awoke' ;)?
thanks Samuel, great bug. will take a look

**Comment by spencermountain** [comment]
got it. will be in v11, hopefully this week.
cheers

**Comment by daedalus28** [comment]
Awesome, thank you! 😄
