### ISSUE TITLE
Ngrams larger than 3

### ISSUE THREAD

**Issue by DirkStevens** [nlp-compromise/compromise#409]
Hello, I can't seem to find the way to get ngrams with size > 3 ?  Is this possible with Compromise?

**Comment by spencermountain** [comment]
hey, yeah the options object may not be working, it seems
https://runkit.com/spencermountain/59aeef955b98ae0012d879a0
i got it to make ngrams with `size==4`, for what it's worth.
but i think the [weird, undocumented](https://github.com/nlp-compromise/compromise/blob/dde2b005133103e83bfe2550e790e1e9e2d868e8/src/text/subset/ngrams/index.js#L1) way for changing this may be busted.
will look into it, hopefully this week

**Comment by DirkStevens** [comment]
Thanks @spencermountain  would be great !

**Comment by DirkStevens** [comment]
Hello @spencermountain you got any chance to look at this?

**Comment by spencermountain** [comment]
hey Dirk, yeah I got it, but it's behind a few other features in the v11 release.
in dev, you can now do this:
```js
var arr = nlp('one two three four five, one two three four five, one two three four five')
  .ngrams({ max: 5 })
  .data();
```
if you just one grams of one size, instead of `max`, use `size`
that cool?
cheers

**Comment by DirkStevens** [comment]
Perfect @spencermountain , both are really useful.

**Comment by spencermountain** [comment]
hey Dirk, workin now
https://runkit.com/spencermountain/59efd6ddadbf4a0011f76240
cheers
