### ISSUE TITLE
Mini bug report ('edit' Gerund results in 'editting')

### ISSUE THREAD

**Issue by emrul** [nlp-compromise/compromise#411]
Just found this project and am poking around with it, very nice piece of work so congratulations to the author and contributors!

I found a small issue that I thought worth reporting:

`nlp("edit").verbs().conjugate()[0].Gerund`

results in 

> editting

but it should only have one 't'.

**Comment by spencermountain** [comment]
thanks Emrul!
will check it out.

**Comment by spencermountain** [comment]
hey, fixed in v11.
https://runkit.com/spencermountain/59efd74c4565c30012d46e15
thanks!
