### ISSUE TITLE
Custom Abbreviations in sentence-splitter

### ISSUE THREAD

**Issue by sebilasse** [nlp-compromise/compromise#413]
Currently it seems not to be possible to use `Abbreviation` from my own lexicon because the sentence splitter uses only the built in lexicon

see
https://github.com/nlp-compromise/compromise/blob/9e621ae96cd94df5f13fd02c0e5d57ba15be0896/src/text/tokenize.js

> const abbreviations = Object.keys(require('../lexicon/uncompressed/abbreviations'));

**Comment by spencermountain** [comment]
this is a good point.
maybe we should work this into v11.
finding all the Abbreviation keys in a big object would be slow, but it would allow this

**Comment by spencermountain** [comment]
gonna combine this with #353 
will try to fit it in v11.1.0
