### ISSUE TITLE
Crash in normalize()

### ISSUE THREAD

**Issue by DirkStevens** [nlp-compromise/compromise#415]
@spencermountain this happens in the latest dev...

nlp("I had a 1-1 meeting.").normalize();

This crashes:
TypeError: ts.terms.forEach is not a function at compromise/builds/compromise.js:11556:14

**Comment by spencermountain** [comment]
ah, thanks.
yeah, dev is 🕶 .
will check it out.
cheers

**Comment by spencermountain** [comment]
hey thanks, works now!
https://runkit.com/spencermountain/59efd7b123124e0011649850
