### ISSUE TITLE
doc.nouns(...).toSingle is not a function

### ISSUE THREAD

**Issue by adam-cowley** [nlp-compromise/compromise#422]
I'm not sure whether I've done something wrong here but I'm getting a `doc.nouns(...).toSingle is not a function` error when trying to convert a noun.  I've tried a few options before finally copying the example directly [from the docs](https://github.com/nlp-compromise/compromise/wiki/Nouns#noun-inflection).

First tried with 11.0.2, then upgraded to 11.1.0.

```
// package.json
  "dependencies": {
    "compromise": "^11.1.0"
  }
```

```
// index.js
const nlp = require('compromise');

var doc = nlp('dinosaur')
doc.nouns().toSingle()
doc.out('text')
```

`nouns().toPlural()` works as expected.

Have I missed something?

_(Superb library by the way)_

**Comment by spencermountain** [comment]
hey Adam, ah thanks.
yeah, looks its the docs. the Method is `nouns().toSingular()`.
you can check it out [here](https://runkit.com/spencermountain/59fb18b0d46b99001121c6a8)

my bad!
p.s. neo4j is a really fun database. cheers
