### ISSUE TITLE
"Have you ever been to France" does not parse as a Question.

### ISSUE THREAD

**Issue by JSdc** [nlp-compromise/compromise#424]
A little more info: I am running the text input as a voice input - the speech is run through Google, and returned as a text string - there are never question marks. I see that may cause some challenges.

parsed.questions().data().length results in Zero for the above phrase.

"Will You..." also does not show as a 'question'.
"Can you explain something for me" also does not.

**Comment by spencermountain** [comment]
hey thanks @JSdc, good eye. 
will check it out this week

**Comment by spencermountain** [comment]
hey, sorry for the delay. got this fixed today.
will be part of today's release.
cheers
