### ISSUE TITLE
Ambiguous parsing

### ISSUE THREAD

**Issue by wizzard0** [nlp-compromise/compromise#426]
It would be great to enable compromise to have multiple interpretations of words, like
"show me your papers" and "he's running a show".
Then, we could start from all permutations of a sentence, and cut off ones that don't match.
Potentially this means exponential complexity, of course, but as compromise meant to do compromises, it might just fall back to the most probable one after some limit.

Somehow related, Nearley parser seems to be a good fit for this (as it supports any kinds of ambiguous context free grammars easily).

**Comment by wizzard0** [comment]
I can try to workaround this with permutations of vocabularies, or rules, and keeping the intermediate results manually, but it would quickly become cumbersome if the same word occurs many times within a single sentence.

**Comment by wizzard0** [comment]
Looking closer, Issue #312 also seems to be related here.

**Comment by spencermountain** [comment]
hey Oleksandr, thanks, I'd never seen nearley.js before. that's pretty neat.
yeah, you're right about how we've been shy about doing any statistical tagging. 
we do a considerable-amount of sentence-level post-processing though, to catch ambiguous word-users. you can see we get ["running the show"](https://runkit.com/spencermountain/5a0f2f330333c00012ed067b) correctly, at least ;)

as of last version, it's become really easy to set these post-hoc transformations yourself, with the [plugin api](https://github.com/nlp-compromise/compromise-plugin).
```
var nlp=require('compromise')
var plugin={
  patterns:{
    "#Gerund (a|an) [#Verb]":'Noun'
  }
}
nlp.plugin(plugin)
var doc=nlp('she is running a show')
doc.match('show').out('tags')[0]
//Noun!
```
https://runkit.com/spencermountain/5a0f31ed5f47c000128aa1a2
cheers

**Comment by spencermountain** [comment]
"show me your papers" & "he's running a show"
both work now in 11.2.1
thanks

**Comment by spencermountain** [comment]
https://runkit.com/spencermountain/5a17879ee39bc6001212f8b4
