### ISSUE TITLE
Context-sensitive parsing

### ISSUE THREAD

**Issue by wizzard0** [nlp-compromise/compromise#427]
For ambiguous parsing mentioned with #426 , there are cases where the ambiguities could be resolved using external information, like
"topic: tech" may enable treating "apple" as "organization", "topic: twitter" enables different treatment of abbreviated words, and so on.
(Yes, this smells of huge datasets, and I'm thinking mainly of node.js usage, but still.)

Similarly, it would be nice to have some convenient option to extract and preserve disambiguated terms from one text to another, to be more stable when working with streaming data, like replicas in the chat, but that is even more handwavy.

**Comment by spencermountain** [comment]
ha! been handwaving for a long time!
yeah, we have a lot of this context-stuff now possible with plugins/lexicon stuff, please read [the wiki](https://github.com/nlp-compromise/compromise/wiki/Plugins)
gonna close this, and refer to 426
