### ISSUE TITLE
date parser examples fail in strange ways

### ISSUE THREAD

**Issue by sandro-pasquali** [nlp-compromise/compromise#428]
Hi, 

Node 8.9.0
npm 5.5.1
OSX latest
compromise: 11.1.0
Tested on: Fri Nov 17, 2017

Running the `.dates()` examples here: http://compromise.cool/

I'm reflecting output of: `console.log(JSON.stringify(nlp(...).cmd().cmd()))` in my tests

```
const nlp = require('compromise');

nlp('Finally, I just stopped caring. Luckily for me, it was 1980 and no one noticed.').dates().data()
// expected: [{text:'1980'}]
// received: []

nlp('April, June, and Sept').dates().toShortForm().all().out()
// expected: Apr, Jun, and Sept
// received: "mar may and Sept" 

nlp('Apr, June, and Sept').dates().toLongForm().all().out()
// expected: April, June, and September
// received: "april, June, and september" (note case)

Note: the longForm example code on that page mistakenly copies the shortForm example; I changed it for the test.
```
Thanks for the great library. I hope that I just missed something obvious.

**Comment by spencermountain** [comment]
hey thanks Sandro, yeah looks like a couple bugs. i'm particularly worried about the ones returning the wrong months. will check it out. 
thanks for the help.

**Comment by spencermountain** [comment]
whoa yeah, nice find.
i fixed the year-as-number one, and the bad one and it will be in the next release.
i'll keep it open until the title-case issue is fixed

**Comment by spencermountain** [comment]
hey, these are [passing now](https://github.com/nlp-compromise/compromise/blob/f00b3b48e1a0cdb2c21fa36325901c7a097126cc/test/unit/subset/date/misc_date.test.js#L25), as of 11.2.1
cheers!

**Comment by sandro-pasquali** [comment]
@spencermountain wow. Thanks!
