### ISSUE TITLE
Match Syntax Scoring

### ISSUE THREAD

**Issue by jhnferraris** [nlp-compromise/compromise#429]
Thanks for the cool NLP library!

Just out of curiosity, does your `.match` have some kind of score? Sort of 

```
let matches = nlp('John eats glue!').match('john eats glue').out('score')
// 0.99 match
```

**Comment by spencermountain** [comment]
hey John! No, the `.match()` stuff is pass/fail, but that's a neat idea, what applications were you thinking of?
you [can see](https://github.com/nlp-compromise/compromise/blob/c9f2a49a137cfe4bb06cb73567144e169d941a04/src/tagger/corrections/index.js) it's pretty central to how things work internally, so it's pretty precious about speed. But it'd be neat to try fuzzy-matching of some kind, lemme know what you have in mind

**Comment by jhnferraris** [comment]
Hi Spencer. yeah I reviewed the code and it is a pass/fail kind. 

My use case is working around AWS Lex. I have this set of "missed utterances" and want to assign them automatically to an existing intent where the utterance matches with the missed one given a certain score.

For now I am using [string_score](https://github.com/joshaven/string_score) for the scoring criteria.

**Comment by playground** [comment]
@spencermountain does or will it support fuzzy matching?

**Comment by spencermountain** [comment]
hi @playground no it does not. You can always [drop-into a regex](https://github.com/nlp-compromise/compromise/wiki/Match-Syntax#actual-regex-) from .match though.
