### ISSUE TITLE
Multi-tenancy: different lexicons

### ISSUE THREAD

**Issue by astanciu** [nlp-compromise/compromise#431]
Trying to figure out the best way to have compromise loaded with different lexicons in a multi-tenant app. I see some reference to this topic in #257 but the recommendation there to pass in different lexicon does not work. For ex, this:

```Javascript
const tenant1 = {
  ssh: 'Resource',
  vpn: 'Resource'
}
const tenant2 = {
  ec2: 'Resource'
}

let doc = nlp('give me ssh', tenant1)
console.log(doc.match('#Resource').out('normal'))  // ssh

let doc2 = nlp('give me vpn', tenant2)
console.log(doc2.match('#Resource').out('normal'))  //vpn
```

doc2 should NOT match "vpn", but it does. Am I doing something wrong or is there a suggested method to have multiple 'instances' of nlp?

**Comment by astanciu** [comment]
Just discovered .clone()... maybe this is the way to go:

```Javascript
let nlp2 = nlp.clone()
let doc = nlp2('give me ssh', tenant1)
console.log(doc.match('#Resource').out('normal'))     //ssh  OK

nlp2 = nlp.clone()
let doc2 = nlp2('give me vpn', tenant2)
console.log(doc2.match('#Resource').out('normal'))   // undefined OK
```

**Comment by spencermountain** [comment]
hey alex, yeah this is possible using `.addWords(lex)` instead of passing them as a 2nd param
you can see .clone() running [here](https://github.com/nlp-compromise/compromise/blob/master/test/unit/extend/clone.test.js)
it's pretty new, so let me know how that goes
