### ISSUE TITLE
Suggestion: .not(Match) or .rest()

### ISSUE THREAD

**Issue by WorldMaker** [nlp-compromise/compromise#434]
A pattern that already seems to be emerging in my application's needs is to try to match specific phrases, then grab-bag the remaining text. More particularly, I might first check for values in specific tag phrases like `.match('tape #Value')` then use a basic assumed order for any remaining values. The way I can see to do this currently:

```ts
const doc = nlp('tape 1, elevation 2, 3 and 4') // or maybe '3, 4, elevation 2, tape 1', with order unimportant for "tagged phrases"
const tape = doc.match('tape [#Value]') // => 1
const elev = doc.match('elevation [#Value]') // => 2
const rest = doc.not('tape #Value')
    .not('elevation #Value')
    .values()
    .numbers() // => [3, 4]
```

I see a couple things that could be done to simplify this code. One is a `.rest()` equivalent to `.all()` that "zooms out" to everything excluding the match. The other would be a version of `.not()` that can accept an existing `.match()` Match object (so far as a brief skim would indicate, it does not currently support that), so that the above might become:

```ts
const doc = nlp('tape 1, elevation 2, 3 and 4') // or maybe '3, 4, elevation 2, tape 1', with order unimportant for "tagged phrases"
const tape = doc.match('tape [#Value]') // => 1
const elev = doc.match('elevation [#Value]') // => 2
const rest = doc.not(tape)
    .not(elev)
    .values()
    .numbers() // => [3, 4]
```

Or maybe:

```ts
const doc = nlp('tape 1, elevation 2, 3 and 4') // or maybe '3, 4, elevation 2, tape 1', with order unimportant for "tagged phrases"
const tape = doc.match('tape [#Value]') // => 1
const elev = tape.rest().match('elevation [#Value]') // => 2
const rest = elev.rest()
    .values()
    .numbers() // => [3, 4]
```

Both options could come in handy. Also, let me know if maybe I just overlooked an existing tool for this.

**Comment by spencermountain** [comment]
you may be able to call `.splitOn(tape)` and pass-in the actual match.
i don't actually remember if this is implemented yet, but that would be another way to do it.
