### ISSUE TITLE
People name recognition problem

### ISSUE THREAD

**Issue by lucasvalenteds** [nlp-compromise/compromise#435]
It seems that there's a problem with `people()` method regarding names. The test below using [Ava](https://github.com/avajs/ava) and compromise `11.2.1` fails at detecting `Mary` name, but changing it to `Monica` it passes.

```javascript
import test from 'ava';
const nlp = require('compromise')

test('American names can be found in a phrase', async t => {
    const phrase = nlp('Mary and John has been a couple since high school')

    const names = phrase.people().out('array')
    const [mary, john] = names

    t.is(2, names.length) // Error: names.length should be 1
    t.is(mary, 'mary')
    t.is(john, 'john')
})
```

Am I missing some rule about name detection?

**Comment by spencermountain** [comment]
hey lucas, naw you haven't missed anything. 'mary' is just an ambiguous name, because it's sometimes a verb.
you can co-erce words to specific interpretations using the [plugin](https://github.com/nlp-compromise/compromise/wiki/Plugins) stuff. It's (intented to be) pretty-easy.
```,
doc=nlp('Mary and John has been a couple since high school', {mary:'Person'})
doc.people().debug()
// mary #Person
// john #Person
```
cheers!

**Comment by lucasvalenteds** [comment]
Thank you for the clarification, @spencermountain. Adding `{mary: 'Person'}` as you mentioned makes the test pass :)
