### ISSUE TITLE
Docs page has 404

### ISSUE THREAD

**Issue by sobopla** [nlp-compromise/compromise#439]
The docs page is missing [](http://compromise.cool/docs)
I was looking to find out if compromise handles indefinite pronouns?

**Comment by spencermountain** [comment]
hey, thanks Catherine. Where is the broken link? on the readme or the wiki?
we don't have a  indefinite pronoun tag, but we probably should. 
fwiw, since there's only a dozen-or-so of them, you can search for them with a `.match()`:
```
nlp(myText).match('(another|anybody|anyone)')
```
PRs welcome!

**Comment by sobopla** [comment]
Hi Spencer
When I click on

   1. is your answer in the official docs <http://compromise.cool/docs>?

   ​The docs page at http://compromise.cool/docs has the 404.

   Also is Is that the actual way to search for them with the pipes in
   between, re: (another|anybody|anyone)
   ?​
   ​
   ​ Just curious, I've only been developing a year and this is new to me.
   ​

​If you have anytime to chat, I'd love to show you what I'm working on. My
goal is to create a small library that will most likely incorporate
compromise into it or something like it.
Compromise sometimes picks two word nouns, i.e.: 'endless varieties', and
two word verbs, i.e. 'started producing'. So that is an edge case I'll have
to work out. It's all a learning process for me.

Thank you for compromise! It's great and really fun to work with! I'll try
to make a pronoun tag PR as my first open source contribution!

Cj
​
​

**Comment by spencermountain** [comment]
agh, thanks!
i'll fix the link in the new year. lemme know if i can help
cheers

**Comment by sobopla** [comment]
I'd love your help! I'm excited to make a fun library using yours in it! (inspired by a children's book  😃

**Comment by hboylan** [comment]
@spencermountain we can haz docs plz? 😄

**Comment by spencermountain** [comment]
hey thanks, this is now just a section of the main website, https://nlp-compromise.github.io/#docs
cheers!
