### ISSUE TITLE
Noun toSingular() wrong output for 'circus' 

### ISSUE THREAD

**Issue by monbro** [nlp-compromise/compromise#440]
Hi,

when using 

````
var doc = nlp('circus');
doc.nouns().toSingular();
word = doc.out('text');
console.log(word);
````

will output `circu`. Which is wrong I see in https://en.wiktionary.org/wiki/circus

**Comment by monbro** [comment]
The same with `clothes`.
Background: I am processing a list of names where i try to normalise them by putting them all into singular (as I don't know exactly if the input is singular or not already.)

**Comment by spencermountain** [comment]
hey thanks Michael, i will look at this next week when i'm back.
in the mean-time, you can use a [plugin](https://github.com/nlp-compromise/compromise/wiki/Plugins) to fix these bad transformations:
```
var plugin={
   plurals:{
      circus: 'circuses',
     clothes: 'clothes'
  }
}
nlp.plugin(plugin)
```
cheers!

**Comment by spencermountain** [comment]
hey Michael, i think i got this one, will be deployed as a new release later today.
cheers
