### ISSUE TITLE
Issue with NLP on the name "Will"

### ISSUE THREAD

**Issue by a-kinder** [nlp-compromise/compromise#445]
We are using compromise to detect if a name is a plural noun or not, and uses that to decide whether to add `'`or `'s` to the end of the name. This works perfectly for most names, but fails on the name "Will". I'm assuming this is because it is a proper noun, an improper noun, a regular verb and an auxiliary verb.

The error returned is as follows:

```
TypeError: undefined is not a function (evaluating 'terms.find(function (t) {       return t.captureGroup === true;     })')
```

Is there any way to resolve this? Right now we just have a try/catch to handle this and any other edge cases. This is the context of the function:

```
      try {
            var words = name.split(' ');
            var lastWord = words[words.length - 1];
            var info = nlp(lastWord).out('tags');
            var tags = info[0].tags;

            //if the last word of the sentence is a plural noun, that ends in s, add '
            if (lastWord[lastWord.length - 1] === 's' && tags.indexOf('Noun') !== -1 && tags.indexOf('Plural') !== -1) {
                name += "'";

                //if not, and it's not already Possessive, add 's
            } else if (tags.indexOf('Possessive') === -1) {
                name += "'s";
            }

        } catch (err) {
            console.error(err);
            name += "'s"
        }

        return name;
```

**Comment by a-kinder** [comment]
Edit: This error only throws when running a script through PhantomJS, doesn't seem to be an issue when running in the browser. I'll close this for now to make sure this isn't an oversight on our end.

**Comment by spencermountain** [comment]
oh hey, that sounds like a neat use-case.
that `terms.find(...` sure looks like a compromise runtime error 😨  - can you isolate it?
I tried 'Will' but couldn't get it to throw.

once we get this figured-out, i'd be happy to help with that method - it may be possible to just do:
```js
nlp(name).has('#Plural$')
```
or something,
cheers

**Comment by a-kinder** [comment]
Thanks for getting back to me. I think I've isolated it to where it throws, it seems to be in the onlyCaptureGroup method. I believe the matches for Will make it through that 'forEach' loop (and other names don't seem to) and that's where it breaks. Ive also discovered that the `terms` parameter seems to be a circular referencing object.

```
var onlyCaptureGroup = function onlyCaptureGroup(matches) {
  var results = [];
  matches.forEach(function (terms) {
    //if there's no capture group, we good.
   //Will dies here <---------------------
    if (terms.find(function (t) {
      return t.captureGroup === true;
    }) === undefined) {
      results.push(terms);
      return;
    }
    //otherwise, just return them as seperate subsets
    var current = [];
    for (var i = 0; i < terms.length; i += 1) {
      if (terms[i].captureGroup) {
        current.push(terms[i]);
      } else if (current.length > 0) {
        results.push(current);
        current = [];
      }
    }
    if (current.length > 0) {
      results.push(current);
    }
  });
  return results;
};
```

**Comment by spencermountain** [comment]
thx, I'll check it out today

**Comment by spencermountain** [comment]
oh, figured it out. [array.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) isn't available in old browsers/runtimes. I just removed it. Will be in the next release, later today.
thanks!

**Comment by a-kinder** [comment]
Thanks a mil!
