### ISSUE TITLE
Britishize asymmetry with Americanize

### ISSUE THREAD

**Issue by AbhinavMadahar** [nlp-compromise/compromise#61]
On version 1.1.3

If you try typing in something like

``` javascript
require("nlp_compromise").britishize("color");
> "color"

require("nlp_compromise").britishize("favorite");
> "favorite"

require("nlp_compromise").britishize("internationalization");
> "internationalization"
```

It just returns whatever the input is.

The americanize function works perfectly fine, though.

![Relevant polandball](http://punkd.org/wp-content/uploads/2013/12/Bloody-Yanks.png)

**Comment by AbhinavMadahar** [comment]
Also, converting from British to American will make "are" to "aer" in the same way "metre" becomes "meter"

**Comment by spencermountain** [comment]
haha! thanks Abhinav. It is way stronger going one way than the other. I'll take a look at improving this, and that bug, this week.
cheers

**Comment by DanielBaird** [comment]
Shot in the dark: maybe try `britishise()` ?

**Comment by spencermountain** [comment]
with the new api (released this week), it's mostly the same call
```javascript
var nlp=require("nlp_compromise")
t=nlp.term("favorite")
console.log(t.britishize())
```
although the asymmetry between britishize and americanize remains. it just needs some work.

**Comment by nathanmarks** [comment]
@spencermountain Here's a demo with a few terms not working as hoped:

1. britishization not working
2. britishization not working
3. americanization works
4. americanization incorrect

https://tonicdev.com/569fd5d4a6f5cc0d0018195d/569fd5d4ff73f00e00779a00

**Comment by spencermountain** [comment]
ah, rats. k thanks.
i'll take a look
thought: should it be renamed to 't.toAmerican(), t.toBritish()'? 
or something else?

**Comment by nathanmarks** [comment]
@spencermountain xxxxxxxx-ize seems to be the norm for a lot of functions in "inflection" libs (dasherize, humanize, camelize, parameterize). FWIW [Americanization is a thing](https://en.wikipedia.org/wiki/Americanization) which is a nice touch.

**Comment by spencermountain** [comment]
;)  copy that.

**Comment by spencermountain** [comment]
locale was removed from this repo a couple months ago, so will close this ticket.
hope to get back into it though, one day
