### ISSUE TITLE
"does [Verb]"  lumping support

### ISSUE THREAD

**Issue by creatorrr** [nlp-compromise/compromise#88]
Hey,

I know I have been reporting a deluge of bugs but I really want to help fix them. :)
Here's another one:

``` javascript
let text = new NLP.sentence("He does not care");
textB.to_present().text();  // -> He does not cares
```

**Comment by spencermountain** [comment]
hey this is great, i'm workin on this in a new branch, *sentence_subclass*.
should be a few days.

**Comment by creatorrr** [comment]
Sweet. Thanks for the update!

**Comment by johnyesberg** [comment]
Oops. In 4.10.6 it says
> new nlp.sentence("He does not care.").to_present().text()
'He does nots cares'

**Comment by spencermountain** [comment]
yeah, so the reason why this is failing is that `does not care` ought to be one big verb term, as opposed to `"does not", "care"`, it's really a tokenization problem.

this is a great example, and something i'll gonna take a look at.

**Comment by spencermountain** [comment]
hey diwank, this situation has been improved in v7, though it could use some work still..
https://runkit.com/583f2a3dc534df0014136221/58c81ef1ee89c00015029109

@johnyesberg yours is fixed now too
https://runkit.com/583f2a3dc534df0014136221/58c81f2b4637b5001471db87
thanks!
