### ISSUE TITLE
Tokenisation without tagging option

### ISSUE THREAD

**Issue by dday34** [nlp-compromise/compromise#94]
Hi guys,

First of all, thanks a lot for this great library.

In my company we are using the version 1.1.4 in production. We recently tried to update to the last version however its seems to be substantially slower than the old to do sentence tokenisation. As an exemple a function that use to take only 25ms to run now takes 822ms so it is 32 times slower. The issue  being that we have to process quite a lot of documents so this will impact a lot our application.

Thanks for your help.

Damien

**Comment by spencermountain** [comment]
hi Damien, thanks for this. I was worried about this being an issue.
What's happened I think is that we've started pos-tagging by default, as it was depended on in so many methods. There's probably a much smarter way to do this just-in-time, or lazily. Which would make way more sense in your use-case.
In the mean-time if sentence tokenization is all you need, [it's not too sophisticated](https://github.com/nlp-compromise/nlp_compromise/blob/master/src/text/sentence_parser.js) and stable if you wanted to pull-it-out and use it independently. 
I'll look into lazy-tagging in the next few weeks. Thanks for your help.

**Comment by dday34** [comment]
ok perfect, thanks we are going to use the sentence parser for now and follow the repo for any updates.

**Comment by spencermountain** [comment]
this works now in the .tokenize() method,
https://runkit.com/spencermountain/59a159b567b6e60012f6dd28
cheers
